### ISSUE TITLE
MacOS: Add Brew package

### ISSUE THREAD

**Issue by a1ad** [GyulyVGC/sniffnet#10]
It would be handy to have a Brew install method.

**Comment by GyulyVGC** [comment]
I noticed @chenrui333 created a Sniffnet Brew package yesterday.
@chenrui333 thank you very much! Can you please give me some info on how to keep the package up to date when I'll publish the next releases?

**Comment by GyulyVGC** [comment]
Closing the issue. Now Sniffnet can also be installed with:
```sh
brew install sniffnet
```

[Here](https://github.com/Homebrew/homebrew-core/pkgs/container/core%2Fsniffnet) you can find the corresponding brew package.
