### ISSUE TITLE
Can't start sniffnet

### ISSUE THREAD

**Issue by roland-rollo** [GyulyVGC/sniffnet#11]
**Describe the bug**

I installed `sniffnet` via cargo and do  `sudo setcap cap_net_raw,cap_net_admin=eip ~/.cargo/bin/sniffnet`
and try after this start `sniffnet`, I see this in terminal
```
thread 'main' panicked at 'Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed', /home/roland/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:619:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**To Reproduce**
Describe steps to reproduce the bug, e.g.:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
`Linux, Sway in Wayland only mode`
v1.0.0 sniffnet
rustc 1.65.0 (897e37553 2022-11-02)

**Additional context**

**Comment by GyulyVGC** [comment]
I'm afraid it is due to Wyland needing some further configuration.

I used iced for the GUI, but I've found your same issue [here](https://github.com/emilk/egui/discussions/1587) for the egui library.

Let me know if you can solve the problem with the link above.

**Comment by roland-rollo** [comment]
It's strange, but... I deleted my `~/.cargo` folder and build every cargo app I have and deleted folder `sniffnet_reports` and now `sniffnet` run with `libpcap` blessing without problem. Huh. I tried in alacritty and wezterm. If I can only ask for one thing: Is there option to quit with combination control+q in future?

**Comment by GyulyVGC** [comment]
I'm happy you managed to run Sniffnet!

On my Mac I'm actually able to quit the app with cmd+q, I'll check and try to make it work on Linux as well.

**Comment by pepa65** [comment]
It would be great if `sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/sniffnet` could be an included step in the `.deb` installer, otherwise users will run into an error on first start.

**Comment by GyulyVGC** [comment]
> It would be great if `sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/sniffnet` could be an included step in the `.deb` installer, otherwise users will run into an error on first start.

Btw, it has been finally included in the latest release!
