### ISSUE TITLE
Changing the height of the Window causes a crash

### ISSUE THREAD

**Issue by hojjatabdollahi** [GyulyVGC/sniffnet#12]
**Describe the bug**
Changing the height of the Window causes the program to crash with this error:
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `iced_wgpu encoder`
    In a set_scissor_rect command
    Invalid ScissorRect parameters
````

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. Install using `cargo install`
2. run the program and press `Run!`
3. Start dragging using the bottom edge and go slowly up shrinking the window
4. When the height of the window is around 3cm it will crash.

**Screenshots**

![Peek 2022-11-21 14-44](https://user-images.githubusercontent.com/2222199/203164371-c2b5c839-44e9-43f5-ba7d-a17ed39c3b29.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**

**Comment by GyulyVGC** [comment]
Thank you for having described the issue!

It has never happened to me, but to solve this I've just set a minimum size for the window!
