### ISSUE TITLE
Display dropped packet stats

### ISSUE THREAD

**Issue by arctic-alpaca** [GyulyVGC/sniffnet#135]
**Is your feature request related to a problem? Please describe.**
Packets might get dropped if sniffnet cannot handle them fast enough. As far as I can tell, the amount of dropped packets is currently not displayed anywhere.

**Describe the solution you'd like**
Some form of information about dropped packets.

**Describe alternatives you've considered**
I'm not sure whether there are alternatives to get this information.

**Additional context**
The pcap crate provides information about captures via the [`stats()`](https://docs.rs/pcap/1.0.0/pcap/struct.Capture.html#method.stats) function. As the docs state, this information can be limited as described here: https://www.tcpdump.org/manpages/pcap_stats.3pcap.html

**Comment by GyulyVGC** [comment]
Thanks for having pointed out, I'll add this feature in the next release!

**Comment by GyulyVGC** [comment]
[A new release](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.2.0) including dropped packets number has just been published!
