### ISSUE TITLE
Permission denied on macOS

### ISSUE THREAD

**Issue by thistehneisen** [GyulyVGC/sniffnet#14]
**Describe the bug**
<img width="797" alt="Screenshot 2022-11-22 at 10 46 30" src="https://user-images.githubusercontent.com/6432992/203267666-cd783e5c-61ce-4c94-9451-4d76ce8c7dcd.png">

**To Reproduce**
1. Install the macOS app via dmg file
2. Run it for the first time with the right click => Open
3. Try to capture packets from en0

**Expected behavior**
Should probably ask for privileges to run with admin rights

**Desktop (please complete the following information):**
 - macOS Ventura 13.0.1

**Comment by thistehneisen** [comment]
I don't think that'd be secure, as from that point on basically any script and program could use the interface without any additional privileges required. Not what I want here.

**Comment by GyulyVGC** [comment]
What would you suggest? Just running Sniffnet as root on MacOS?

**Comment by thistehneisen** [comment]
What I tried to articulate in "Expected behavior" but failed to do properly was that upon clicking the "Run!" button there's a check for (a lack of) privileges. If they're lacking — the script should probably run with `sudo` to access the `/dev/bp*` interfaces, triggering the macOS [built-in password dialog](https://www.wikihow.com/images/thumb/1/18/Reset-a-Lost-Admin-Password-on-Mac-OS-X-Step-21-Version-2.jpg/aid175869-v4-728px-Reset-a-Lost-Admin-Password-on-Mac-OS-X-Step-21-Version-2.jpg).

**Comment by GyulyVGC** [comment]
Yeah, I will definitely implement a dialog like that in the next release in case of missing privileges.

In the meantime, a not-so-nice workaround is to open Sniffnet executable from a terminal in `sudo` mode

**Comment by GyulyVGC** [comment]
> Running with `sudo` did not work for me either on **macOS Ventura 13.0.1**:
> 
> 
> 
> `sudo open /Applications/Sniffnet.app` ends in same error.

Right click on the .app file and look at its content. 
You will find an executable file, copy the executable path and then try launching it with sudo.

Show me a screenshot if the error persists.

**Comment by macuserguru** [comment]
I think .... this need
a) a signature from a verified apple developer
or
b) an unlock in one of the items in the system settings

I know something similar with .kext .dext files in other apps. They needs an unlock too.
So as BIND named (installed with Homebrew) needs unlocking the ports.

**Comment by moortaube** [comment]
> > Running with `sudo` did not work for me either on **macOS Ventura 13.0.1**:
> > `sudo open /Applications/Sniffnet.app` ends in same error.
> 
> Right click on the .app file and look at its content. You will find an executable file, copy the executable path and then try launching it with sudo.
> 
> Show me a screenshot if the error persists.

`sudo /Applications/Sniffnet.app/Contents/MacOS/sniffnet` did now work.  
Maybe I had to restart or I misspellt command trying with executable path.

Btw: Now `sudo open /Applications/Sniffnet.app` did not start your app anymore.

Thanks for now.

**Comment by GyulyVGC** [comment]
If you now try to open the app it won't start because you have previously launched it in sudo mode and a textual report has been written as root. If you try to restart the app, it will try to delete the file but it will fail since it has been created as root. If you remove the report with `sudo rm -rf ~/sniffnet_report` you will be able to launch the .app again.

However, I'm currently working to fix this problem.

**Comment by robertovalerio** [comment]
Log in as root and run the App via CLI does work:

```
su
/Applications/Sniffnet.app/Contents/MacOS/sniffnet ; exit;
```

**Comment by GyulyVGC** [comment]
I have good news.

I managed to solve the problem by including a wrapper script in the app bundle:

```
#!/bin/sh
#!/bin/sh
osascript -e '
    tell app "Terminal"
        do script "sudo /Applications/Sniffnet.app/Contents/MacOS/sniffnet"
        activate
    end tell
'
```

Basically, it opens a new terminal launching Sniffnet in sudo mode, requiring the user to insert a password.

If you guys could try to install again through the installer and tell me if it works on your system, it'd be awesome.

You can find the updated installer [here](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.0.0)

**Comment by GyulyVGC** [comment]
I'm closing this issue: I've tried on a different Mac and it works fine.

Also I updated the script as follows: `sudo /*/Sniffnet.app/Contents/MacOS/sniffnet`

I introduced the `*` wildcard to make it work even if your machine's language is not English and you have the `Applications` folder that actually has a different name.

**Comment by moortaube** [comment]
I have tried it and it worked fine for me, too.
Thank you!
