### ISSUE TITLE
Mangled UI display

### ISSUE THREAD

**Issue by dr-kristau** [GyulyVGC/sniffnet#15]
**Describe the bug**
Mangled UI display

**To Reproduce**
From bash, run sniffnet:
`$ sniffnet`
I also get the following warning:
`MESA-INTEL: warning: Haswell Vulkan support is incomplete`

**Screenshots**
![Screenshot from 2022-11-22 10-59-12](https://user-images.githubusercontent.com/32355001/203284601-eb1ed072-824f-4225-906b-14da70a80437.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Version 1.0.0

**Comment by GyulyVGC** [comment]
Are you able to set `RUST_BACKTRACE=full` and post here the full shell output?

**Comment by dr-kristau** [comment]
I've tried:
`$ RUST_BACKTRACE=1RUST_BACKTRACE=full sniffnet`

but it doesn't seem to give me anything further:
![Screenshot from 2022-11-22 11-21-50](https://user-images.githubusercontent.com/32355001/203289716-ae065e05-d50b-43e1-abb8-31ba964355f6.png)

**Comment by GyulyVGC** [comment]
I've found an issue similar to yours [here](https://github.com/iced-rs/iced/issues/422).

Let me know if it helps.

**Comment by dr-kristau** [comment]
Thanks!

When I try with `cargo install` I get:

```bash
$ cargo install --features glow,glow_canvas sniffnet
    Updating crates.io index
  Installing sniffnet v1.0.0
error: failed to compile `sniffnet v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installWgWv81`

Caused by:
  none of the selected packages contains these features: glow, glow_canvas
```
When I can, I'll download the source and try `cargo build` on it.

**Comment by GyulyVGC** [comment]
Yeah, I suggest you to clone the repository and build it locally on your machine providing the flag with those features.

I'm leaving open the issue, feel free to come back to give me updates on this problem, I'd really appreciate it! 

Thank you for having opened this issue.

**Comment by dr-kristau** [comment]
Okay, I've cloned the source and built but get the same message. In fact I've cloned the iced repo, run the clock example, and I get the same message:

```bash
$ cargo build --features glow,glow_canvas --package clock
error: none of the selected packages contains these features: glow, glow_canvas
```

Clearly something has changed. If I do a `cargo run` on the iced clock example without the` --features` I get a mangled UI just the same as I've reported for this repo.

**Comment by GyulyVGC** [comment]
Yeah, iced has been updated since that issue.

Another possible solution would be to try adding those features in the Cargo.toml file, in the iced features section.

On my Kali distro it works without problems, so I don’t know what to do to reproduce the issue on my machine.

If you are going to dig into the problem and you can find a solution, you can then open a pull request and that’d be awesome.

**Comment by GyulyVGC** [comment]
The GUI library I used relies on wgpu and [here](https://github.com/gfx-rs/wgpu#supported-platforms) you can find the supported platforms and API. 

Try checking issue #17 and let me know. Even if you don't have problems on the start phase, it could be still something related to graphic dependencies missing on your platform.

**Comment by dr-kristau** [comment]
> The GUI library I used relies on wgpu and [here](https://github.com/gfx-rs/wgpu#supported-platforms) you can find the supported platforms and API.

Thank you for thinking of me!

Unfortunately, none of the wgpu examples I've tried work on my machine, in fact they don't run at all. 

```bash
$ cargo run --example hello
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/examples/hello`
MESA-INTEL: warning: Haswell Vulkan support is incomplete
```
This means that the problem is definitely not yours, but is a problem I have with wgpu. Thank you again for your help.

**Comment by GyulyVGC** [comment]
Hi @dr-kristau 
I know a lot of time has passed, but some weeks ago I setup a secondary branch `glow-renderer` which uses `glow` as graphical renderer instead of `wgpu`and I think that it should solve your problem!

**Comment by dr-kristau** [comment]
Good work @GyulyVGC, and thank you :smiley: 

On my Fedora box I had to install a couple of packages to get the `glow-renderer` branch to compile, namely:
1. `alsa-lib-devel`
2. `libpcap-devel`

And then I could finally build and run `sniffnet`!

**Comment by GyulyVGC** [comment]
Amazing ❤️
Ps: an rpm package which include those dependencies will also be available on the release pages!
