### ISSUE TITLE
Packet PDUs Export

### ISSUE THREAD

**Issue by sujitawake** [GyulyVGC/sniffnet#162]
Are you planning to provide support for exporting the packets to either PCAP or PCAPng format?

**Comment by GyulyVGC** [comment]
I have other plans in the short term, but in the long term I’ll consider adding support for PCAP format

**Comment by GyulyVGC** [comment]
Sniffnet finally supports exporting PCAPs 🎉 

This feature has just been merged into the main branch and will be officially released shortly as part of version 1.3.0.
