### ISSUE TITLE
Glitchy UI

### ISSUE THREAD

**Issue by arnabanimesh** [GyulyVGC/sniffnet#163]
**Describe the bug**

The display looks like this:
<img width="960" alt="Screenshot 2023-04-23 171040" src="https://user-images.githubusercontent.com/6032584/233837899-cd66248c-c8ba-4df9-8f6f-7dd9e0ff12d3.png">

The white boxes are me censoring the hardware and IP addresses

**To Reproduce**
Describe steps to reproduce the bug:
Open sniffnet 1.1.4 (installed via cargo) on a 1920x1080 resolution hi dpi screen with 150% scaling (Intel UHD Graphics 620; Win 11 latest)

**Expected behavior**
Show GUI properly

**Screenshots**
Already added

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser NA
 - Version 1.1.4

**Additional context**
Ran the app with `RUST_BACKTRACE=full` and there were no error logs.

**Comment by GyulyVGC** [comment]
You can try running the app from the `glow-renderer` branch, which uses a different renderer and most of the times this solves the problem

**Comment by GyulyVGC** [comment]
@arnabanimesh can you please confirm that switching to the `glow-renderer` solves the problem? 
Thanks in advance!

**Comment by arnabanimesh** [comment]
@GyulyVGC `glow-renderer` is working fine. It should be the default IMO.

**Comment by GyulyVGC** [comment]
I'm happy to know it's working well for you!

I think that wgpu has more compatibility in general though, and for this reason iced set it as default.
