### ISSUE TITLE
Icon is too Big compared to other ones (macOS)

### ISSUE THREAD

**Issue by itfidele** [GyulyVGC/sniffnet#177]
**Screenshots**
<img width="286" alt="Screenshot 2023-05-14 at 00 22 20" src="https://github.com/GyulyVGC/sniffnet/assets/30210556/0c8f46e5-64c0-4687-9d65-5b6e3937f09a">

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by GyulyVGC** [comment]
[A new release](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.2.0) solving this issue has just been published!

![image](https://github.com/GyulyVGC/sniffnet/assets/100347457/20197e2b-af9f-4187-b84b-ccfd600f53d0)
