### ISSUE TITLE
Unable to launch sniffnet

### ISSUE THREAD

**Issue by Sudodoc** [GyulyVGC/sniffnet#18]
Please, help me to solve this probllem while launching the app

:~$ sniffnet
sniffnet: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by sniffnet)

___________________________

OS: LMDE 5 (elsie) x86_64
Kernel: 6.0.0-0.deb11.2-amd64

**Comment by GyulyVGC** [comment]
Did you install Sniffnet through cargo or through the .deb package?

**Comment by Sudodoc** [comment]
Through the .deb package. The installation through cargo was unsuccessful. I got an error like this:

error: failed to run custom build command for `yeslogic-fontconfig-sys v3.2.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installvwnUYb/release/build/yeslogic-fontconfig-sys-9e5767d61a81af44/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RUST_FONTCONFIG_DLOPEN
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "`\"pkg-config\" \"--libs\" \"--cflags\" \"fontconfig\"` did not exit successfully: exit status: 1\nerror: could not find system library 'fontconfig' required by the 'yeslogic-fontconfig-sys' crate\n\n--- stderr\nPackage fontconfig was not found in the pkg-config search path.\nPerhaps you should add the directory containing `fontconfig.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'fontconfig' found\n"', /home/alexey/.cargo/registry/src/github.com-1ecc6299db9ec823/yeslogic-fontconfig-sys-3.2.0/build.rs:8:48
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sniffnet v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installvwnUYb`

**Comment by GyulyVGC** [comment]
Try again to install with cargo after the command `sudo apt-get install libfontconfig libfontconfig1-dev`

It seems some version of Linux miss some packages needed to build correctly Sniffnet.

You'll probably get other error like this after having installed `libfontconfig`, but let me know if it works.

**Comment by GyulyVGC** [comment]
Nice! 

Closing this issue then!
