### ISSUE TITLE
UDP/80 is not 'HTTP'

### ISSUE THREAD

**Issue by amarao** [GyulyVGC/sniffnet#188]
I've noticed that UDP ports are named according to TCP port names.

![image](https://github.com/GyulyVGC/sniffnet/assets/652496/c20a0b60-2802-423d-a151-83c4b774359d)

**Comment by GyulyVGC** [comment]
Thanks for having pointed out.
As explained [here](https://github.com/GyulyVGC/sniffnet#supported-application-layer-protocols), the determination of application protocols is very basic for now.

I'll have to polish it up in the upcoming releases.

**Comment by GyulyVGC** [comment]
I've noticed that different resources state that both TCP and UDP port 80 is HTTP, such as https://httplab.it/PortDef, https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers or https://www.geeksforgeeks.org/50-common-ports-you-should-know/.

Any suggestion?

**Comment by amarao** [comment]
Oh, it's Quick, and it uses UDP/80, and call it HTTP. Okaaay. If Google hijacked HTTP name for own protocol, what can we do... UDP/80 it is.
