### ISSUE TITLE
Crash on Windows 10 right after start

### ISSUE THREAD

**Issue by gwselke** [GyulyVGC/sniffnet#19]
sniffnet crashes on Windows 10 durectly after start with this message and backtrace:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:50:70
stack backtrace:
   0:     0x7ff7b0f873b1 - <unknown>
   1:     0x7ff7b0d412ea - <unknown>
   2:     0x7ff7b0f6f8c9 - <unknown>
   3:     0x7ff7b0f895ab - <unknown>
   4:     0x7ff7b0f891c5 - <unknown>
   5:     0x7ff7b0f89ef9 - <unknown>
   6:     0x7ff7b0f89dda - <unknown>
   7:     0x7ff7b0f89d69 - <unknown>
   8:     0x7ff7b0f89d24 - <unknown>
   9:     0x7ff7b111e515 - <unknown>
  10:     0x7ff7b111e60c - <unknown>
  11:     0x7ff7b0ed87ac - <unknown>
  12:     0x7ff7b0ee2106 - <unknown>
  13:     0x7ff7b0ed68d8 - <unknown>
  14:     0x7ff7b111d18c - <unknown>
  15:     0x7fff4c5774b4 - BaseThreadInitThunk
  16:     0x7fff4e4226a1 - RtlUserThreadStart

To reproduce:
Just start sniffnet.exe from the Windows 10 command lne.

I would expect to see the sniffed traffic.

Desktop : Windows 10

**Comment by GyulyVGC** [comment]
The application panics because it is not able to find a suitable network adapter on your PC.

Did you install the dependencies I mentioned in the README? Did you correctly setup your LIB environment variable?

**Comment by GyulyVGC** [comment]
I'm closing this issue, check the README or #1 to install the needed dependencies for Windows systems.

**Comment by gwselke** [comment]
My mistake -- a typo in my LIB path, I should have double-checked.. I'm sorry for the false alarm. Works perfectly!
