### ISSUE TITLE
Installing on RHEL based systems

### ISSUE THREAD

**Issue by phxyz12** [GyulyVGC/sniffnet#20]
Dear developers

**Is your feature request related to a problem? Please describe.**
We use RHEL based systems (CentOS and Rocky Linux) and currently, there are no rpm packages available for sniffnet.

**Describe the solution you'd like**
We would love to see rpm packages and/or an instruction for compiling and building sniffnet from source.

**Describe alternatives you've considered**
None.

**Additional context**
None.

Kind regards,

Pascal

**Comment by GyulyVGC** [comment]
Can you install it with `cargo`?

**Comment by rafal06** [comment]
So, maybe an AppImage?

**Comment by GyulyVGC** [comment]
@phxyz12 @rafal06 after some delays, I've finally come up with an rpm package for Sniffnet.
Could you kindly try if it works fine? Thanks in advance.

[sniffnet-1.2.0-1.x86_64.rpm.zip](https://github.com/GyulyVGC/sniffnet/files/11492415/sniffnet-1.2.0-1.x86_64.rpm.zip)

**Comment by GyulyVGC** [comment]
[A new release](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.2.0) including the RPM package has just been published!

**Comment by GyulyVGC** [comment]
An AppImage for Sniffnet is landing with the next release!

I'd be really grateful if you could let me know if it works on CentOS and other less popular distros.

[Sniffnet_LinuxAppImage_amd64-2.AppImage.zip](https://github.com/user-attachments/files/21566781/Sniffnet_LinuxAppImage_amd64-2.AppImage.zip)

Remember to launch it as sudo to correctly monitor network adapters.

Thanks in advance.
