### ISSUE TITLE
Wpcap.dll not found

### ISSUE THREAD

**Issue by altilunium** [GyulyVGC/sniffnet#201]
**Describe the bug**
![image](https://github.com/GyulyVGC/sniffnet/assets/70379302/4cfafa42-b2ce-41d2-8a04-21a6bd94aca3)

**To Reproduce**
Install sniffnet, install npcap, add npcap sdk to `LIB` environment variable, run sniffnet.

**Expected behavior**
Sniffnet is running

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Additional context**
If possible, where can I ((safely)) download wpcap.dll? How to install it?

**Comment by GyulyVGC** [comment]
This is an issue related to your npcap installation probably, as someone already solved it in the past:

> Solved: Reinstalling Npcap and selecting `WinPcap API-compatible mode` solved the issue. I was not aware that this setting had to be used.

Let me know.

**Comment by altilunium** [comment]
Thank you. It's working now :)

![image](https://github.com/GyulyVGC/sniffnet/assets/70379302/fcac8bab-410d-4843-9385-d20eda79530b)
![image](https://github.com/GyulyVGC/sniffnet/assets/70379302/04083454-7011-487c-9fd8-f8a85bca1c80)

**Comment by GyulyVGC** [comment]
Awesome, I hope you will like Sniffnet!
