### ISSUE TITLE
Der Prozedureinsprungspunkt 'pcap_set_immediate_mode" wurde in der DLL "C:\Program Files"\sniffnet\bin\sniffnet.exe" nicht gefunden

### ISSUE THREAD

**Issue by P7aM5qzEddT66lE** [GyulyVGC/sniffnet#21]
Black windows on screen and messagebox after start:
Der Prozedureinsprungspunkt 'pcap_set_immediate_mode" wurde in der DLL "C:\Program Files"\sniffnet\bin\sniffnet.exe" nicht gefunden
[OK]
After click on [OK] messagebox and black window close.

I've WinPcap 4.1.3 (latest version) installed
Just starting Sniffnet by clicking the icon. No difference when starting as administrator.

**Expected behavior**
No error msgbox and starting normally.

**Comment by GyulyVGC** [comment]
Are you running on Windows? Have you correctly setup the LIB environment variable?
Have you installed Sniffnet through the installer or via cargo?

**Comment by P7aM5qzEddT66lE** [comment]
THX for immediate reaction! Great support!

I allready solved the issue:
Due to a report about Sniffnet on heise.de about Sniffnet, where the page with the windows installer msi is directly linked I haven't read the dependencies on https://github.com/GyulyVGC/sniffnet. I found that page by random.

After installing npcap (with uninstalling WinPcap) Sniffnet starts and works as expected.

Maybe on the installer page a link to the dependencies  had been useful for me.

**Comment by GyulyVGC** [comment]
Thanks you very much for your suggestion!

I'll add a link to the required dependencies.

**Comment by P7aM5qzEddT66lE** [comment]
Disclaimer:
I just installed npcap (with WinPcap compatible API, which uninstalled WinPcap) to get it work.
I haven't installed the npcap sdk and didn't set the LIB var on my system. My sniffnet installation works without those two.

**Comment by GyulyVGC** [comment]
Could be that maybe you already had wincap in your LIB variable? 

If you can check it would be nice.

**Comment by P7aM5qzEddT66lE** [comment]
I've allready checked that - and now double checked it after reboot.
Neither in system var nor in user var there's a LIB var.

And I searched my system for the libs which are in the sdk i.e. packet.lib and wpcap.lib
There are wpcap.dll's on my computer (System32, SysWOW64) but no wpcap.lib and no packet.lib.

Sniffnet still works fine.

**Comment by GyulyVGC** [comment]
Weirdly enough, I didn't manage to run it on Windows 10 without setting the LIB env var.

I'm happy you managed to make it work though!
