### ISSUE TITLE
Sniffnet doesn't start

### ISSUE THREAD

**Issue by escafora** [GyulyVGC/sniffnet#211]
OS Windows 11
Followed dependencies instructions and obtaining this:

![Screenshot 2023-05-21 175210](https://github.com/GyulyVGC/sniffnet/assets/77228481/19f32203-81a1-45f4-b577-6c4324b6f2ad)

**Comment by ch-devhost** [comment]
I have the same problem

**Comment by GyulyVGC** [comment]
@escafora @ch-devhost you have to install npcap in compatible mode with Winpcap. 
See #201 to solve the problem

**Comment by GyulyVGC** [comment]
Since it seems to be a recurring problem, I have also updated the docs: 38c3e3a

Let me know in case of further doubts.

**Comment by GyulyVGC** [comment]
More specifically, this issue is a duplicate of #21 and #86, which were solved with the aforementioned step or by changing Npcap version.

**Comment by escafora** [comment]
OK, it works now! Thank you.

**Comment by GyulyVGC** [comment]
> OK, it works now! Thank you.

No problem! 
I'm happy it works 💖
