### ISSUE TITLE
Graphics card incompatibility?

### ISSUE THREAD

**Issue by ThoralfSchade** [GyulyVGC/sniffnet#218]
Hi,
Unfortunately, my graphics card seems to be incompatible with the great program:
 [https://bit.ly/43iv1Dk](https://bit.ly/43iv1Dk)
Or does anyone have an idea where the flickering comes from and what can be done about it?
Best regards and thanks for the help.

**Comment by ThoralfSchade** [comment]
Win 11 Pro

**Comment by GyulyVGC** [comment]
Ok. I'll build for you a version of the program using a different graphical renderer, hoping this will solve the problem

**Comment by ThoralfSchade** [comment]
Oh ha, that's very nice but also very elaborate.
Am I the only one affected by this error ?

**Comment by GyulyVGC** [comment]
You are not the only one, but it's pretty unusual.

The GUI library I use allows choosing between 2 different renderers (`wgpu` and `glow`).
I've already set up a `glow-renderer` branch for cases like this one.

Here you are the fresh built executable:
- [sniffnet-1.2.0-x86_64.msi.zip](https://github.com/GyulyVGC/sniffnet/files/11554493/sniffnet-1.2.0-x86_64.msi.zip)

**Comment by ThoralfSchade** [comment]
That is really very nice, thank you very much, I will try it out later....

**Comment by GyulyVGC** [comment]
No problem man, let me know if it works 👍

**Comment by GyulyVGC** [comment]
Amazing!
I'm always glad to help ❤️
