### ISSUE TITLE
Error while installing on Linux Mint 19.3

### ISSUE THREAD

**Issue by JumpOverWires** [GyulyVGC/sniffnet#22]
When installing via "cargo install sniffnet", I got the following error message:

> error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/tmp/cargo-installpg8AVH/release/deps/sniffnet-141f9bfdac14a619.sniffnet.40c2eb61-cgu.15.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installpg8AVH/release/deps" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/usr/lib/x86_64-linux-gnu" "-L" "/tmp/cargo-installpg8AVH/release/build/plotters-iced-9b76ee91b244b54c/out" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcQjMUR3/libplotters_iced-64964f1fde9f8b2b.rlib" "-Wl,--start-group" "-Wl,--end-group" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-3e693007a886e005.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lfontconfig" "-lfreetype" "-lpcap" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installpg8AVH/release/deps/sniffnet-141f9bfdac14a619" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs"
  = note: /usr/bin/ld: cannot find -lpcap
          collect2: error: ld returned 1 exit status
          

error: could not compile `sniffnet` due to previous error
error: failed to compile `sniffnet v1.0.0`, intermediate artifacts can be found at `/tmp/cargo-installpg8AVH`

1. I first installed cargo via terminal (sudo apt install cargo) with no errors
2. I tried to install sniffnet via terminal  (cargo install sniffnet)

The install-process took quite long and after reaching "compiling sniffnet" it stopped with the above mentioned error message.

**Desktop**
 - OS: Linux Mint 19.3 Cinnamon 
 - Browser Firefox
 - Version 107.0
 
![error_message_sniffnet](https://user-images.githubusercontent.com/27350067/203526049-3d44bd34-d7fe-4ad6-81d0-c56ef9ab6c51.png)

**Comment by GyulyVGC** [comment]
You don't have lpcap, have you checked the README? Section Install and Run -> Linux dependencies

**Comment by GyulyVGC** [comment]
I'm closing the issue since it clearly seems due to some missing dependencies, feel free to reopen it if the problem persists.
