### ISSUE TITLE
Downloaded RPM, crashes on start (XDG_RUNTIME_DIR)

### ISSUE THREAD

**Issue by SpaceRaccoonFluff** [GyulyVGC/sniffnet#220]
**Describe the bug**
I'm using Fedora 38. I downloaded the RPM and when I go to open the app, the terminal opens up asking me for my password. Once I put the password in the sniffnet logo and some text that I can't read before the terminal window vanishes/crashes 1 second later after entering my sudo password. 

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. Go to https://www.sniffnet.net/download/ and download RPM
2. Double click to install it.
3. Click the icon or "open" button in Software Center
4. Enter in your sudo password
5. Watch as it crashs.

**Expected behavior**
For the GUI to open up and let me use the app. Also why does clicking the icon open up my terminal instead of the GUI app from the start?

**Desktop (please complete the following information):**
 - OS: Linux Fedora 38

**Additional context**
Is this a dependency issue? I did not install any, If so I am pretty new to linux overall still and need help with the exact commands for Fedora specifically to properly install them. Thanks to anyone who can get this working, I really need a GUI based bandwidth monitor and I want to like this one.

**Comment by SpaceRaccoonFluff** [comment]
I went ahead and sudo dnf installed those 3 but it's still crashing when I open it and type in my password in the terminal.

**Comment by SpaceRaccoonFluff** [comment]
I had to record it and watch it frame by frame since the terminal crashes in less than a second after typing in the password but this is what I was able to capture before crashing/closing: https://imgur.com/a/lnLpdvu

**Comment by GyulyVGC** [comment]
I also got that error but it was more like a warning in my case because the app was able to correctly run anyway.
I'll come back to you if I have any news.

**Comment by GyulyVGC** [comment]
I remember of a guy who solved this exact problem in #17.
You can check how he solved it.

**Comment by SpaceRaccoonFluff** [comment]
Something about wgpu and x11. I use wayland on Fedora. Is that why the GUI is not showing up? If so what would the command to fix it be?

**Comment by GyulyVGC** [comment]
I honestly have no idea, but at this point I think that the problem is related to the graphical renderer.
If you have Rust installed, I suggest you to build Sniffnet from the [`glow-renderer`](https://github.com/GyulyVGC/sniffnet/tree/glow-renderer) branch, which usually solves renderer-related problems.

**Comment by GyulyVGC** [comment]
Hey @SpaceRaccoonFluff 

We changed the building strategy and we are looking for feedback/testers to see if we finally solved this issue.

Could you kindly try the new package available below?

[Sniffnet_LinuxRPM_x86_64.rpm.zip](https://github.com/GyulyVGC/sniffnet/files/11682048/Sniffnet_LinuxRPM_x86_64.rpm.zip)

Thanks in advance.
