### ISSUE TITLE
Typo on Windows 10 Start Menu

### ISSUE THREAD

**Issue by bgodole** [GyulyVGC/sniffnet#223]
When installing Sniffnet under Windows 10, a folder and a shortcut to the software is created in the Start Menu. The shortcut reads "Sniffet" instead of Sniffnet.

![sniffnet](https://github.com/GyulyVGC/sniffnet/assets/15838230/4e8c9957-558a-440e-942c-0ee9d960abaf)

**Comment by GyulyVGC** [comment]
Thank you very much for having pointed out!
