### ISSUE TITLE
error: XDG_RUNTIME_DIR not set in the environment

### ISSUE THREAD

**Issue by maravento** [GyulyVGC/sniffnet#228]
**Describe the bug**

## Install:

```
sudo apt install libpcap-dev libasound2-dev libfontconfig1
VER=$(curl -s https://api.github.com/repos/GyulyVGC/sniffnet/releases/latest|grep tag_name|cut -d '"' -f 4|sed 's/v//')
wget https://github.com/GyulyVGC/sniffnet/releases/download/v${VER}/sniffnet_Linux.deb
sudo dpkg -i sniffnet_Linux.deb
sudo setcap cap_net_raw,cap_net_admin=eip /usr/bin/sniffnet
```
## Run:
```
sudo sniffnet
```
## Error:
```
error: XDG_RUNTIME_DIR not set in the environment
```
## Screencapture:

![sniffnet](https://github.com/GyulyVGC/sniffnet/assets/14880802/19cddd2b-ba68-46b9-adbd-94c359675fbf)

## Attempts to fix the problem (no results):
```
sudo pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /usr/bin/sniffnet
# or
sudo pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY QT_X11_NO_MITSHM=1 /usr/bin/sniffnet
# or
sudo -u myuser bash -c 'pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY /usr/bin/sniffnet'
```
## Log:
```
may 30 09:08:05 mst pkexec[184485]: root: Executing command [USER=root] [TTY=/dev/pts/1] [CWD=/home/user] [COMMAND=/usr/bin/env DISPLAY=:0 XAUTHORITY=/home/user/.Xauthority QT_X11_NO_MITSHM=1 /usr/bin/sniffnet]
may 30 09:08:20 mst pkexec[184535]: root: Executing command [USER=root] [TTY=/dev/pts/1] [CWD=/home/user] [COMMAND=/usr/bin/env DISPLAY=:0 XAUTHORITY=/home/user/.Xauthority /usr/bin/sniffnet]
```
## Workaround: 
1. Create a bash script call sniffnet.sh with content:
```
#!/usr/bin/env bash
/usr/bin/sniffnet &>/dev/null &
```
2. And run:
```
sudo chmod +x sniffnet.sh
sudo ./sniffnet.sh
```
### Note: the error doesn't come out if i run it without "sudo"
```
sudo setcap 'cap_net_raw,cap_net_admin=eip' $(which sniffnet)
sniffnet
```

SO: Ubuntu MATE 22.04.2 LTS x86_64

**Comment by GyulyVGC** [comment]
Hi @maravento 

Could you kindly try running it with `sudo -E sniffnet` and check if that message persists?
Can you also confirm that it doesn't cause any usability issue?

**Comment by GyulyVGC** [comment]
> ### Note: the error doesn't come out if i run it without "sudo"
> ```
> sudo setcap 'cap_net_raw,cap_net_admin=eip' $(which sniffnet)
> sniffnet
> ```

This is the best thing you can do.
And I would like to make it as default for the next versions (see #224 where we discussed about it).

**Comment by maravento** [comment]
> Hi @maravento
> 
> Could you kindly try running it with `sudo -E sniffnet` and check if that message persists? Can you also confirm that it doesn't cause any usability issue?

the error does not come out with the "-E" option. Thanks

However what worries me about running this program is that I can't send it to the background. If I close the terminal window, the program closes
So, I have to run it with a bash script (store it anywhere. example: `/etc/init.d/sniffnet.sh` with the following content):
```
#!/usr/bin/env bash
/usr/bin/sniffnet &>/dev/null &
```
and modifying the `/usr/share/applications/sniffnet.desktop` file:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Sniffnet
Comment=Application to comfortably monitor your network traffic
Categories=Network;Security;Utility;
Icon=sniffnet
Exec=/etc/init.d/sniffnet.sh
StartupWMClass=sniffnet
Terminal=false
```

**Comment by GyulyVGC** [comment]
> the error does not come out with the "-E" option. Thanks

Amazing, thanks for the confirmation
 
> However what worries me about running this program is that I can't send it to the background. If I close the terminal window, the program closes So, I have to run it with a bash script (store it anywhere. example: `/etc/init.d/sniffnet.sh` with the following content):

This is a really important point, see [this file](https://github.com/GyulyVGC/sniffnet/blob/main/resources/wrapper.sh): this is how I solved the issue on macOS, very similar to what you did.

But what I think it's the best thing to do is setting capabilities to inspect a network adapter with sudo setcap..., and then launching without opening the terminal (I'll try to implement this feature as a post install script).

> So, Is there any other way to run the app in the background, without the terminal open?

Sure, if you run `sudo setcap 'cap_net_raw,cap_net_admin=eip' usr/bin/sniffnet` you should be able to launch sniffnet without opening the terminal and without sudo privileges.
So you could edit the original .desktop file removing sudo and setting terminal to false.

**Comment by maravento** [comment]
solved!
```
[Desktop Entry]
Version=1.0
Type=Application
Name=Sniffnet
Comment=Application to comfortably monitor your network traffic
Categories=Network;Security;Utility;
Icon=sniffnet
Exec=/usr/bin/sniffnet
StartupWMClass=sniffnet
Terminal=false
```

Thanks. Great app. Great job

PD: I know from experience that these jobs are very time-consuming. But I hope you keep in mind at some point, to be able to access this app, via WEB-GUI (http://localhost:port):, to be able to work on servers without a desktop.

**Comment by maravento** [comment]
Installation proposal (at least for Ubuntu 22.04.x):
```
sudo apt install -y libpcap-dev libasound2-dev libfontconfig1
LASTVERSION=$(curl -s https://api.github.com/repos/GyulyVGC/sniffnet/releases/latest|grep tag_name|cut -d '"' -f 4|sed 's/v//')
wget https://github.com/GyulyVGC/sniffnet/releases/download/v${LASTVERSION}/sniffnet.deb
sudo dpkg -i sniffnet.deb
sudo setcap 'cap_net_raw,cap_net_admin=eip' /usr/bin/sniffnet
sudo sed -i -e 's/^Exec=sudo \/usr\/bin\/sniffnet$/Exec=\/usr\/bin\/sniffnet/' -e 's/^Terminal=true$/Terminal=false/' /usr/share/applications/sniffnet.desktop
```
