### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` - when "Open full Report" button is pressed

### ISSUE THREAD

**Issue by vosskaem** [GyulyVGC/sniffnet#23]
**Describe the bug**
After pressing the button "Open full Report" the program is crashing.

**To Reproduce**
1. Install in your user with: cargo install sniffnet
2. sudo sniffnet
3. press Run 
4. press Open full Report
5. see error

**Expected behavior**
See some advanced report

**Program start**
This is before error:
`sudo sniffnet 
[sudo] Passwort für myuser: 
error: XDG_RUNTIME_DIR is invalid or not set in the environment.`

**Error**
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffnet-1.0.0/src/gui/app.rs:102:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/myuser/.cargo/registry/src/github.com-1ecc6299db9ec823/sniffnet-1.0.0/src/gui/app.rs:102:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/result.rs:1814:5
   3: iced_winit::application::update
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: iced_winit::application::run::{{closure}}
   6: winit::platform_impl::platform::EventLoop<T>::run_return
   7: iced_winit::application::run
   8: sniffnet::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Desktop:**
 - OS: EndeavourOS + Gnome

**Comment by GyulyVGC** [comment]
I think it could be related to issue #13.
Can you try opening the file manually? The app creates a sniffnet_report folder in the same directory where it has been launched.

**Comment by vosskaem** [comment]
The file is there. Looks ok for me.

**Comment by vosskaem** [comment]
I can confirm that it works after
`sudo ln -s /usr/bin/xdg-open /usr/bin/open`

**Comment by GyulyVGC** [comment]
Then the problem could be the same as the issue linked above: I already updated the code on GitHub with `xdg-open` over `open` but still I have not published an updated release for that.
