### ISSUE TITLE
GUI flashing/blinking

### ISSUE THREAD

**Issue by MZCKKeepcool** [GyulyVGC/sniffnet#232]
hello,

I have issues with the GUI that keeps on blinking and flashing, with or without moving the mouse and whether in full screen or not.
see attached screenshots.

I just installed the Windows version 1.2.0, and the PC is running Windows 10 Prod 22H2.
The dependencies have been checked (NPCAP  1.75 installed as advised and environment variables added to the NPCAP SDK folder)
I will try to find another computer, running a different version of Windows OS to check.

anyone has/had the issue?

![Sniffnet-blink](https://github.com/GyulyVGC/sniffnet/assets/53711051/d8e93b53-a4e5-40de-8bba-635047aeac91)
![Sniffnet-blink2](https://github.com/GyulyVGC/sniffnet/assets/53711051/86a326d6-c14c-462e-8fa6-10554a5435e2)

**Comment by GyulyVGC** [comment]
This is a known issue which happens on some system not supporting the default `wgpu` renderer.
I've created a version of the app which uses another renderer (`glow`) which usually solves the problem.
Check https://github.com/GyulyVGC/sniffnet/issues/218 to know more about this issue. There you will find a file to download which contains the same version of the app but using the alternative renderer.

Let me know if this solves the problem.

**Comment by MZCKKeepcool** [comment]
Thank you very much, it's working great now.
Sorry for the duplicate

**Comment by GyulyVGC** [comment]
> Thank you very much, it's working great now.
> Sorry for the duplicate

I'm happy it's working!
Don't worry 🙌
