### ISSUE TITLE
Windows 10: Faulting module name: nvwgf2umx.dll

### ISSUE THREAD

**Issue by cathsaigh** [GyulyVGC/sniffnet#234]
**Describe the bug**
Upon launch, sniffnet starts up for about 15 seconds and then crashes  - throwing the following error:

Faulting application name: sniffnet.exe, version: 0.0.0.0, time stamp: 0x6464d509
Faulting module name: nvwgf2umx.dll, version: 23.21.13.8795, time stamp: 0x59dbff63
Exception code: 0xc000041d
Fault offset: 0x00000000008f4b48
Faulting process id: 0x4008
Faulting application start time: 0x01d993d5a61e5ed9
Faulting application path: C:\Program Files\sniffnet\bin\sniffnet.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\nvdm.inf_amd64_2499cb38d840b3b4\nvwgf2umx.dll
Report Id: 71b82124-6a0a-40d2-8501-716fd4331d2d
Faulting package full name: 
Faulting package-relative application ID: 

**To Reproduce**
double click on sniffnet.exe icon

**Expected behavior**
launches without issue

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise Build 19045
 - Browser:  Chrome
 - Version 113.0.5672.127 (Official Build) (64-bit)

**Comment by GyulyVGC** [comment]
How did you build Sniffnet? With cargo? Or did you use the installer?

**Comment by cathsaigh** [comment]
The build attached to #218 worked - thanks.

**Comment by GyulyVGC** [comment]
> The build attached to #218 worked - thanks.

Awesome, I'm happy you can now use Sniffnet 🙌
