### ISSUE TITLE
After installing Windows version, getting an execution error related to wpcap.dll

### ISSUE THREAD

**Issue by srinivasakumar-a** [GyulyVGC/sniffnet#240]
**Describe the bug**
Installation of sniffnet on Windows 10 machine was successful. However, when clicked on the windows shortcut to open the application for the first time, I'm getting the following error message and on clicking ok, application does not open!

Error message: "The code execution cannot proceed because wpcap.dll was not found. Reinstalling the program may fix this problem."

I tried reinstalling the application twice, still the error persists. I did a google search on the error and found couple of instructions to get the wpcap.dll from online and placed it in the system folder and restarted the system. Still the error persists.

Attaching the error screenshot for your reference.
![Windows10_Code Execution Error](https://github.com/GyulyVGC/sniffnet/assets/33969314/cf025a17-02f6-42f1-a745-9ca7599d171a)

**Comment by GyulyVGC** [comment]
Hi @srinivasakumar-a 

The problem is that you didn’t install the required dependencies.

Follow the steps described [here](https://github.com/GyulyVGC/sniffnet#required-dependencies) or have a look at #1 for more info.

**Comment by GyulyVGC** [comment]
I'm closing since it's a duplicate of many solved issues.
See also #35, #152, or #201.
Let me know in case of further doubts.
