### ISSUE TITLE
sniffnet: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kdipto1** [GyulyVGC/sniffnet#242]
**Describe the bug**
I installed the deb package. Also i have installed  the dependencies. But its showing this error :-
sniffnet: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

**Desktop (please complete the following information):**
 - OS: Linux
 - Version : 22.04

**Comment by GyulyVGC** [comment]
Duplicate of #199 and #225.
Please refer to #199.
We hope to fix this issue for the next release.
