### ISSUE TITLE
[Feature Request] Option to provide path to own geoip database.

### ISSUE THREAD

**Issue by IncSW** [GyulyVGC/sniffnet#243]
**Is your feature request related to a problem? Please describe.**
To have better ip information accuracy, if you have paid database

**Describe the solution you'd like**
Options like `-geoip-country /path/to/country.mmdb`, `-geoip-asn /path/to/asn.mmdb`

**Comment by GyulyVGC** [comment]
Thanks for the suggestion.
This is something I could consider for the next major release.

**Comment by GyulyVGC** [comment]
Hey @IncSW, a fix to this issue has just been merged to the main branch (implemented as part of #365): now both ASN and Country database paths can be specified via in-app settings.

This and other changes will be officially released in version 1.3.
