### ISSUE TITLE
sniffnet doesn't respect `--help` and `--version` flags

### ISSUE THREAD

**Issue by Aloso** [GyulyVGC/sniffnet#264]
**Describe the bug**
Running `sniffnet --help` or `sniffnet --version` should display information in the terminal without starting the GUI.

**To Reproduce**
1. Run `sniffnet --help` or `sniffnet --version`

**Expected behavior**
The GUI should not start.

`sniffnet --help` should show what CLI flags are supported (it should support at least `--help` and `--version`).

`sniffnet --version` should display the current version.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.2.1

**Comment by GyulyVGC** [comment]
It's definitely something I will implement.
Thanks for pointing out.

**Comment by gautamprikshit1** [comment]
@GyulyVGC any pointers on how to resolve it?

**Comment by GyulyVGC** [comment]
> @GyulyVGC any pointers on how to resolve it?

It's not a problem, but more something that has to be reimplemented.
Sniffnet used to be a CLI in the past and arguments were parsed with `clap`.
I think I will use a similar approach to reintroduce them, launching the app as a GUI only if not present.

**Comment by GyulyVGC** [comment]
Done!
Thanks to @Aloso for having implemented this feature in #272
