### ISSUE TITLE
IPv6 addresses don't fit in the table (Inspect tab)

### ISSUE THREAD

**Issue by Aloso** [GyulyVGC/sniffnet#265]
**Describe the bug**
In the "inspect" tab, IPv6 addresses sometimes occupy 2 or 3 table columns, so the content to the right no longer aligns with the table header:

![image](https://github.com/GyulyVGC/sniffnet/assets/15658558/dfde7f30-cdd7-4b11-8655-ad78c3fa57e4)

And to see all content, it requires vertical scrolling, but this doesn't scroll the table header:

![image](https://github.com/GyulyVGC/sniffnet/assets/15658558/228e82fc-4ea9-4bfc-a34a-c58c583c6cc4)

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. Inspect traffic with IPv6 packets

**Expected behavior**
The table header should always be aligned to the content

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 1.2.1

**Comment by GyulyVGC** [comment]
First of all, thank you very much for opening all this issues since you are finding really interesting points.

In this case it's a duplicate of #63 though.

**Comment by GyulyVGC** [comment]
Happy to announce that #63 is now completely fixed by PR #442.

The relative changes are now in the main branch, and will be officially released in v1.3.0.
