### ISSUE TITLE
Entry Point pcap_set_immediate_mode could not be located

### ISSUE THREAD

**Issue by diamant3** [GyulyVGC/sniffnet#268]
**Describe the bug**
Entry Point pcap_set_immediate_mode could not be located

**To Reproduce**

1. Install the sniffnet(windows 64bit)
2. Click the sniffnet.exe
3. error :(

**Screenshots**

<img width="304" alt="image" src="https://github.com/GyulyVGC/sniffnet/assets/71203851/157280a6-a709-498a-83db-6cd51fb91a1a">

**Desktop:**
 - OS: Windows 11

**Additional context**

I already installed npcap and winpcap but no luck :(

**Comment by diamant3** [comment]
I just ticked the `Install Npcap in WinPcap API-compatible Mode` checkbox. It's fixed now!

**Comment by GyulyVGC** [comment]
Yes, that was exactly the cause as documented in other issues. 

It’s nice you find out it yourself! 👍
