### ISSUE TITLE
Can't run sniffnet on MacOS

### ISSUE THREAD

**Issue by yuta519** [GyulyVGC/sniffnet#28]
**Describe the bug**
(At first, I'm not proficient in OS and NW layers.  So if my question is not clear, I'm sorry and please teach what you can't understand.)

I installed sniffnet on MacOS. But I got a permission error. Please teach me how to fix this.

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. Installed with the below commands
```bash
cargo install sniffnet
cargo run sniffnet
```

2. When GUI appears, choose an interface and click run.

**Expected behavior**

**Screenshots**
I got the below message.

<img width="1192" alt="Screen Shot 2022-11-25 at 18 16 11" src="https://user-images.githubusercontent.com/12853233/203944392-3bd6d8bc-d06b-4de8-b4f5-fe0cc40ce3ec.png">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
![Screen Shot 2022-11-25 at 18 17 00](https://user-images.githubusercontent.com/12853233/203944542-51f4c0db-fdec-42c9-b88d-1a7e1daec9d3.png)

**Additional context**

**Comment by GyulyVGC** [comment]
You will solve the problem just by launching with admin privileges:

`sudo cargo run sniffnet`

**Comment by GyulyVGC** [comment]
Closing the issue, feel free to reopen it if it doesn't work!

**Comment by yuta519** [comment]
@GyulyVGC 
I appreciate your help! I'll try the above command. Thanks.
