### ISSUE TITLE
Terminal UI

### ISSUE THREAD

**Issue by DasFaultier** [GyulyVGC/sniffnet#29]
**Is your feature request related to a problem? Please describe.**
I have a lot of systems that are only accessible via SSH and don't have a GUI installed, either because they're minimized servers/containers and/or because they run on SoC hardware with little resources available. Currently, I cannot use sniffnet on these systems. It would be really handy to be able to use sniffnet on these systems as well, e.g. for finding connections that hint to possible compromise of these systems.

**Describe the solution you'd like**
My suggestion is to make sniffnet available as a terminal unser interface (TUI) software as well, maybe using something like ncurses (I really don't know). If it's not possible to automatically find out if a user wants to run sniffnet in GUI or TUI mode, I'd suggest adding a CLI flag to enter TUI mode (thus keeping the current default of entering GUI if no arg is given).

**Describe alternatives you've considered**
The only alternative that I could think of would be to make sniffnet available via network in a browser and providing the UI in HTML5, because it's universally supported, but a) it would increase attack surface on the system because it means that likely a webserver with an open port is needed and b) it would probably draw more resources as well.

**Additional context**
No actual context, but I just installed sniffnet 1.0.0 on my Linux Mint 21 and I found it really neat. Thank you and keep up the great work!

**Comment by GyulyVGC** [comment]
I'll keep the request into account! [Sniffnet v.0.5.0](https://github.com/GyulyVGC/sniffnet/tree/v0.5.0) was actually a CLI but what it did was just to generate two report files and I think you are speaking about a more comprehensive TUI.

**Comment by DasFaultier** [comment]
> (...) I think you are speaking about a more comprehensive TUI.
That's right, I was imagining something that would regularly update in the terminal and could be used interactively, just like the GUI application, ideally adapting to the terminal size. Not being a developer myself, I'm not even sure if that's feasible with your current implementation, just an idea.

**Comment by 0323pin** [comment]
@DasFaultier You might want to have a look at [netop](https://github.com/ZingerLittleBee/netop)

**Comment by GyulyVGC** [comment]
I am closing this issue as 'not planned'.
After having taken into consideration different possibilities, I've come to the conclusion that it's better for me to focus exclusively on the GUI, as I feel like the vast majority of users is more interested on the graphical interface.
Furthermore, I'm working to add new functionalities to the GUI which would require additional time to be re-implemented also for the TUI (and some of them wouldn't even be feasible).

**Comment by pythops** [comment]
Checkout [oryx](https://github.com/pythops/oryx), might be what you need
