### ISSUE TITLE
segmentation fault when running sniffnet

### ISSUE THREAD

**Issue by 9x3l6** [GyulyVGC/sniffnet#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

# sniffnet

  /---------------------------------------------------------\
 |     _____           _    __    __                  _      |
 |    / ____|         (_)  / _|  / _|                | |     |
 |   | (___    _ __    _  | |_  | |_   _ __     ___  | |_    |
 |    \___ \  | '_ \  | | |  _| |  _| | '_ \   / _ \ | __|   |
 |    ____) | | | | | | | | |   | |   | | | | |  __/ | |_    |
 |   |_____/  |_| |_| |_| |_|   |_|   |_| |_|  \___|  \__|   |
 |                                                           |
 |                   ___________                             |
 |                  /___________\                            |
 |                 | ___________ |                           |
 |                 | |         | |                           |
 |                 | | v1.2.1  | |                           |
 |                 | |_________| |________________________   |
 |                 \_____________/   by Giuliano Bellini  )  |
 |                 / ''''''''''' \                       /   |
 |                / ::::::::::::: \                  =D-'    |
 |               (_________________)                         |
  \_________________________________________________________/
[1]    27240 segmentation fault  sniffnet

### How did you install the app?

downloaded one of the provided packages

### Operating System

macOS

### Additional context

# brew install sniffnet
# sniffnet
unable to run due to segmentation fault

**Comment by GyulyVGC** [comment]
It's most likely due to your graphical adapter being incompatible with the default graphical renderer used by the GUI library, as described in https://github.com/GyulyVGC/sniffnet/issues/176.
There, you will also find the solution.
Let me know if it helps.

**Comment by 9x3l6** [comment]
That worked thanks. It would be nice if I could sort the columns so they didn't jump around, because by the time I click, it might click on what I didn't want, but that would have to be a feature request.

**Comment by GyulyVGC** [comment]
> That worked thanks. It would be nice if I could sort the columns so they didn't jump around, because by the time I click, it might click on what I didn't want, but that would have to be a feature request.

Glad it worked.

Do you mean the rows?
Are you referring to the host table or to the connection table?

**Comment by 9x3l6** [comment]
No! I means the columns, not rows, in the tables. Sort by doesn't have Dest or Src address or port, would be nice to sort by source and destination address and port.

**Comment by GyulyVGC** [comment]
Got it.
To have more stability in the sort order (to click a row in an easier way without the order changing) I can suggest you to order by packets or bytes instead of recent.
I’ve never considered sorting by IP address since it’s less useful generally speaking.
