### ISSUE TITLE
Faster way to write textual report file

### ISSUE THREAD

**Issue by GyulyVGC** [GyulyVGC/sniffnet#3]
I'd like to find a way to write the textual report in less time.
The textual report contains various [address:port] pairs with the relative statistics; as data are collected, it will become a larger file and will be re-written every time interval (5 seconds by default).

If you uncomment the lines from 26 to 28 of the `Cargo.toml` file you will be able to see on the standard output the time taken to write the report.
This is what you will see every time interval:
![Screenshot 2022-09-12 at 18 18 25](https://user-images.githubusercontent.com/100347457/189706385-8249953c-f19c-46ff-ad7b-43a25f053be2.png)

The time I aim to reduce is the "**_Print map_**" time. 
For every entry of the map, the key and the value are printed; I implemented the Display trait for both the key and the value using the `format!(...)` macro.

**_Currently, it takes about 100 ms to print a map of about 3500 entries  (which corresponds to an output file of 50k lines) on my dual core computer._**

I already tried implementing the Display trait using `push_str(...)` on a defined `String::with_capacity(...)` instead of `format!(...)` but the time does not improve.

**Comment by mrghosti3** [comment]
What is being used to print to console? Would be interesting to read how those macros look and test out whether it is better to just write to stdout, stderr via a custom function.

**Comment by GyulyVGC** [comment]
> What is being used to print to console? Would be interesting to read how those macros look and test out whether it is better to just write to stdout, stderr via a custom function.

I use `println!(...)`, but console prints are just a few and they do not impact on the time needed to write the output file.

**Comment by mrghosti3** [comment]
Oh. I misread and though this is about console logging instead of file. Where where the writing is done?

**Comment by GyulyVGC** [comment]
> Oh. I misread and though this is about console logging instead of file. Where where the writing is done?

On a `.txt` file, using a BufWriter.

**Comment by mrghosti3** [comment]
Found the function that writes the report. How is intended to work?

Also instead might suggest to store `/path/to/report.txt` before the loop as to skip `format!()` and String memory allocation:
https://github.com/GyulyVGC/sniffnet/blob/7fc23206a76f826db939c99842c8949beb1a349c/src/thread_write_report_functions.rs#L117

**Comment by GyulyVGC** [comment]
I will do that, thanks.

However, the problem is more related to the following snippet:
https://github.com/GyulyVGC/sniffnet/blob/7fc23206a76f826db939c99842c8949beb1a349c/src/thread_write_report_functions.rs#L134-L138
This loops and prints on the output file many many times, as the map size grows during packets capture.
`key` and `val` are two struct created by me. 
To see how they are printed see how I implemented the Display method in the files `src/address_port_pair.rs` and `src/info_address_port_pair.rs`

**Comment by mrghosti3** [comment]
Firstly, I may not know how iterators fully work so feel free to point it out.

I believe that code below may take up some time, due to it using iterators which are lazy loaded:
https://github.com/GyulyVGC/sniffnet/blob/7fc23206a76f826db939c99842c8949beb1a349c/src/info_address_port_pair.rs#L43-L48

Instead maybe it could be converted using simple `if else` blocks:
```rust
if self.transmitted_bytes < 1000 {
    // do nothing
} else if self.transmitted_bytes < 1000000 {
    n /= 1000_f32;
    multiple_transmitted.push('k');
} else if self.transmitted_bytes < 1000000000 {
    n /= 1000000_f32;
    multiple_transmitted.push('M');
} else {
    n /= 1000000000 as f32;
    multiple_transmitted.push('G');
}
```

**Comment by GyulyVGC** [comment]
I wrote a little benchmark and found that unluckily it doesn't make any difference.

**Comment by mrghosti3** [comment]
Understandable, I guess the compiler does it's own optimisations. I will play around with some code changes on my side when I can share what I can find.

**Comment by GyulyVGC** [comment]
Update: I have introduced the `--verbose` option to print the report as it was before. Now by default the report is printed in a more concise mode and the printing time is about 1/10 of that needed to print the report in verbose mode.

![verbose_concise_benchmarks](https://user-images.githubusercontent.com/100347457/190470320-1aa23f09-0fe3-4bc1-b667-2120135a6c8a.png)

However, I still would like to find out if I can reduce the time needed to print the verbose mode report.

**Comment by auronandace** [comment]
Looking at write_report_file_header() in thread_write_report_functions.rs I can see you have a whole bunch of consecutive write! and writeln! macro calls. Have you tried consolidating them?

I would have thought having them separate would mean you are constantly writing to output several times in a row instead of just in one go.

I must admit the way you have done it now does make it nice and readable. Not sure how ugly it may look lumping them together in a single write! or writeln!.

**Comment by mrghosti3** [comment]
I also think that the compiler doesn't optimize all that `write!` calls. But only way to figure this one out would to either write bench test or to compare compiled exes.

**Comment by auronandace** [comment]
Might be worth using a BufWriter:

https://doc.rust-lang.org/std/io/struct.BufWriter.html says in part: "BufWriter<W> can improve the speed of programs that make small and repeated write calls to the same file or network socket."

If I'm reading your source correctly you seem to be writing to the file directly rather than a buffer.

**Comment by GyulyVGC** [comment]
I already use a BufWriter, therefor those write!(...) calls are just called once per time interval.
And moreover, as you can see in the picture where I showed the timings, the file header printed by that function is written in less than 1 ms, while the time I am aiming to improve is that to print the whole map.

**Comment by auronandace** [comment]
Hmm, so sleep_and_write_report_loop() writes the entire report from scratch at each update interval?

Why did you not go for a more simple append file technique?

It seems rather wasteful to re-write the entire file over and over if only a small portion of the data has changed. From what I can tell the overall stats would need updating and then you just append the latest pair to the end of the file.

**Comment by GyulyVGC** [comment]
Yeah of course I could append at every time interval just the new [address:port] pairs, but I did this way to have a report in which every pair appears just once.

**Comment by auronandace** [comment]
The bigger the file gets then the longer the delay is going to become because you are writing everything all over again.

If you only change what is needed and append only what is new then updating the file is going to take the same amount of time each time you need to update it instead of building up. Are you sure you can't just check the file for duplicate pairs before you write?

I hate to say it but I think it does need a redesign so that you are only doing the work that is required.

**Comment by mrghosti3** [comment]
What if instead overwriting file, the old reports stay there while you write new one say `report1.txt`? This way, when you create a new file, the syscal only allocates new block from disk, instead of truncating the existing file to 0 and then giving you access to the file.

**Comment by GyulyVGC** [comment]
> The bigger the file gets then the longer the delay is going to become because you are writing everything all over again.
> 
> If you only change what is needed and append only what is new then updating the file is going to take the same amount of time each time you need to update it instead of building up. Are you sure you can't just check the file for duplicate pairs before you write?
> 
> I hate to say it but I think it does need a redesign so that you are only doing the work that is required.

This way sounds really better with respect to appending.
Detecting duplicate pairs before inserting them would be easy I think.

 I just need to figure out how to detect the specific line of code where that pair is written in order to rewrite that pair statistics. This could involve a linear search in which I read data from file and check if that entry corresponds to that I am looking for. 
However, this may result in even bigger delay due to the searching time.

**Comment by GyulyVGC** [comment]
Another way could be to keep an updated map in which I track for each pair the line it appears in the output.
In this case however I would need to update that list at every new insertion on the output file.

**Comment by GyulyVGC** [comment]
Also, I could sort the output file on the basis of the timestamp instead of the total packets exchanged. 
In this way the position of a given pair would not change after its first insertion.
Thanks @mrghosti3 and @auronandace for the suggestions, next week I'll try this solution and will update what I have found.

**Comment by GyulyVGC** [comment]
I've found out that it is more complicated than I thought: setting a seek offset for a write is measure in bytes and not in lines and I didn't find a way to set the offset as line number.

**Comment by GyulyVGC** [comment]
I've optimized report writes! 

Now only changed entries are re-written. I implemented this change for concise mode but I'll implement it also for the verbose mode.

Finally closing the issue!

**Comment by mrghosti3** [comment]
@GyulyVGC trying to learn to how to bench code. Where did you write the the benches in this issue and what tools did you use?
