### ISSUE TITLE
"`wpcap.dll` was not found" Error on Windows 11

### ISSUE THREAD

**Issue by scrazzz** [GyulyVGC/sniffnet#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Running Sniffnet after installing throws this error:
![image](https://github.com/GyulyVGC/sniffnet/assets/70033559/c54c4839-4ef7-45fc-ac38-7b67295a2384)

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

### Additional context

I tried deleting the app and re-installing but that didn't work.

**Comment by GyulyVGC** [comment]
As described in the README and in the installer, you have to install Npcap.
You can find it at this link: https://npcap.com/dist/npcap-1.75.exe

Duplicate of many issues (e.g., #1).
Feel free to reopen if you have further problems.

**Comment by scrazzz** [comment]
Right, my bad. I forgot to install the SDK.

**Comment by evaggelosevaggelou** [comment]
I can't run the program, I get this message.

<img width="417" height="192" alt="Image" src="https://github.com/user-attachments/assets/10951be7-4720-41a8-a701-ebbc9355064b" />

**Comment by GyulyVGC** [comment]
Hey @evaggelosevaggelou please follow steps 4 & 5 from this guide: https://github.com/GyulyVGC/sniffnet/wiki/Install-on-Windows
