### ISSUE TITLE
cargo install sniffnet failed on windows 10 msvc toolchain

### ISSUE THREAD

**Issue by zredb** [GyulyVGC/sniffnet#33]
**Describe the bug**
When exceute cargo install sniffnet, the compiler returns  "= note: LINK : fatal error LNK1181: cannot open input file 'wpcap.lib'" errro message. 

**To Reproduce**
Describe steps to reproduce the bug, e.g.:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]

**Additional context**

**Comment by GyulyVGC** [comment]
It seems like you don't have installed the right dependencies on your system.

Check issue #1, your problem has already been solved!
