### ISSUE TITLE
SUGGESTION: Add information about run dependencies if not compiling yourself.

### ISSUE THREAD

**Issue by 38github** [GyulyVGC/sniffnet#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

I had issued finding what package had setcap under OpenSUSE Tumbleweed. I downloaded the Linux x86_64 rpm and spent ten minutes to find out that libcap-progs is a package that I needed. After that I could setcap the options for network non-root users.

### Is your feature request related to a problem?

I didn't see one. If there is I apologise for the duplicate.

**Comment by GyulyVGC** [comment]
Thanks for the suggestion.
However, the main dependencies are already specified [in the README](https://github.com/GyulyVGC/sniffnet#required-dependencies).
Most of Linux distro natively has setcap from my experience, so it'd be difficult to consider all the different possible OS/environments and I've limited to the dependencies needed on the most popular systems.

**Comment by 38github** [comment]
I understand it would be a lot work. Thank you for taking the time to reply.

**Comment by GyulyVGC** [comment]
Do you have any log output anyway?
Wasn't it sufficient to install libpcap?

**Comment by 38github** [comment]
No, libpcap (or libcap1) was not enough and Sniffnet said that it could not connect to... something that I do not remembered. I apologize. I searched google and didn't immediately see an answer to my question but when I ran "cnf setcap" zypper told me that it was in the libcap-progs package.

**Comment by GyulyVGC** [comment]
No worries! 👍
