### ISSUE TITLE
Window too large on Debian Sid in X11

### ISSUE THREAD

**Issue by tripplehelix** [GyulyVGC/sniffnet#344]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

I have both installed the provided deb and built from source from this repo. In both cases the window opens larger than my screen resolution. Only able to resize vertically slightly. This makes the app unusable.

Operating System: Debian GNU/Linux trixie/sid
Desktop Environment: Xfce 4.18
Build Version: 1.2.2

### How did you install the app?

built locally by cloning the repository

### Operating System

Linux

### Additional context

![image](https://github.com/GyulyVGC/sniffnet/assets/16861223/0f7c3db4-69be-406d-8351-aacce83f2801)

**Comment by GyulyVGC** [comment]
Thanks for the report.
What's your screen resolution?

**Comment by GyulyVGC** [comment]
This is also somewhat related to #202, even if not the same issue.
To solve this issue, it'll be necessary to reduce the minimum window size allowed and some widgets won't have enough space, but this additional problem will be solved by defining a lower scale factor as described in #202 
I'll take care of solving both issues before v1.3 is published.

**Comment by tripplehelix** [comment]
> Thanks for the report. What's your screen resolution?

1920x1080

**Comment by GyulyVGC** [comment]
Mmm weird... I've tried Sniffnet in PCs with lower resolutions and everything was fine.
The minimum size currently allowed for the window is 1190x610, but that are logical pixels and not physical ones.
So it depends on how that are converted to physical pixels in your specific case ([source](https://github.com/iced-rs/iced/issues/1006#issuecomment-905503147)).

I think that introducing a scale factor will resolve this issue as well.

**Comment by GyulyVGC** [comment]
@tripplehelix can you try building from [this branch](https://github.com/GyulyVGC/sniffnet/tree/advanced-settings) and let me know if by lowering the scale factor the issue is solved?
You can change the scale factor from the application settings (top right corner of the app) in the rightmost tab (advanced settings).

**Comment by tripplehelix** [comment]
Incredibly difficult getting to the settings with the window so large, this is minimum scale factor and I've dragged the window as small as possible.

![image](https://github.com/GyulyVGC/sniffnet/assets/16861223/16e3a69e-ff45-4ef3-add7-bcf54d3e1462)

**Comment by GyulyVGC** [comment]
I've just adjusted the minimum size allowed for the window in that same branch, meaning that now you should be able to resize the window to fit your screen.

The default window size is kept the same and immediately after the start it is maximised.
I'm curious if the maximise operation immediately adapts the window size to your screen after start, so that you don't have to manually resize it every time.

Let me know when you can.

**Comment by tripplehelix** [comment]
Maximisation doesn't work, it just doesn't let me. That is shrunk to the smallest size, still overflowing screen resolution.

**Comment by tripplehelix** [comment]
> I've just adjusted the minimum size allowed for the window in that same branch, meaning that now you should be able to resize the window to fit your screen.
> 
> The default window size is kept the same and immediately after the start it is maximised. I'm curious if the maximise operation immediately adapts the window size to your screen after start, so that you don't have to manually resize it every time.
> 
> Let me know when you can.

Ok, that works, but the window is double the size it needs to be. By default it opens full screen. With scale factor of 0.5 text and icons look a normal size.

![Screenshot_2023-08-23_14-41-43](https://github.com/GyulyVGC/sniffnet/assets/16861223/112dad24-7149-4ec6-9233-a0ce1bb666b5)
Ignore the error

**Comment by tripplehelix** [comment]
When you un-pin it from full screen it pops to larger than screen resolution.

**Comment by GyulyVGC** [comment]
> Ok, that works, but the window is double the size it needs to be. By default it opens full screen.

So, when you open the app the dimension exactly fits your screen?
What do you mean by the size is double? I'm assuming you mean the scale factor, right?

> ![Screenshot_2023-08-23_14-41-43](https://user-images.githubusercontent.com/16861223/262688065-112dad24-7149-4ec6-9233-a0ce1bb666b5.png)

And this is the situation after you resize it to the minimum, right?

**Comment by tripplehelix** [comment]
> > Ok, that works, but the window is double the size it needs to be. By default it opens full screen.
> 
> So, when you open the app the dimension exactly fits your screen? What do you mean by the size is double? I'm assuming you mean the scale factor, right?
> 
> > ![Screenshot_2023-08-23_14-41-43](https://user-images.githubusercontent.com/16861223/262688065-112dad24-7149-4ec6-9233-a0ce1bb666b5.png)
> 
> And this is the situation after you resize it to the minimum, right?

For me, the window size should be half what its minimum is currently. Yes, that is the minimum size of the window.

When I first open the application it perfectly fits my resolution yes, but enlarges when unpinned.

Scale factor is only fine when set to 0.5 so in my situation this should be default on first install.

**Comment by tripplehelix** [comment]
Here is a comparison between sniffnet and an application built for the OS

![image](https://github.com/GyulyVGC/sniffnet/assets/16861223/4140c2cf-14b1-4e67-8912-6f0d7cdaf22f)

**Comment by tripplehelix** [comment]
I don't believe it all needs to be displayed at once, for example if I am using it to find an erroneous app I'd place the app in a corner of my screen at 1/4th the resolution and scroll around the application to the relevant place. Using the rest of the screen for the terminal, application in question and maybe even the file explorer. Currently the apps seems to want to be the main focus all the time when using it. Also, what if my screen resolution was even smaller? The window would still display over the edges of the screen. 

Why does the app not pull it's text size from the OS?

**Comment by GyulyVGC** [comment]
> Why does the app not pull it's text size from the OS?

The GUI library in use doesn't provide this functionality.

I'm used to keep apps I don't want to be the focus on the background, or on a different desktop.
That's basically why Sniffnet is not thought to be configured for a "pop-up" mode.
This is a feature it could be worked on though...

**Comment by GyulyVGC** [comment]
@tripplehelix hey, the changes we discussed have just been merged to the main branch (implemented as part of #365).

These and other features will be officially released in version 1.3.
