### ISSUE TITLE
Windows10 : wpcap.dll not found at program start

### ISSUE THREAD

**Issue by jwesemann** [GyulyVGC/sniffnet#35]
**Describe the bug**
Sniffnet not starting due to missing dependecy npcap.dll

**To Reproduce**
1. Installed sniffnet using provided MSI
2. Start program using desktop icon
3. Windows opens a "Systemerror window" (screenshot attached)
4. Reinstall (was installed before) NPcap-1.71 again with default options
5. Reboot
6. Start program using desktop icon (again)
7. Windows again opens a "Systemerror window" (screenshot attached)

**Expected behavior**
Program should start, detect needed capture library which is present on the system  and present GUI

**Screenshots**
![sniffnet_windows10_missing_wpcap](https://user-images.githubusercontent.com/43301079/204124249-a99ca2cb-98c5-4bee-ab2c-8fcc539fafbd.jpg)

**Desktop (please complete the following information):**
-  MS Windows 10 , 22H2 , Build 19045.2311
- NPcap 1.71
- Wireshark using same NPcap is working well

**Additional context**
- NPcap SDK (LIB variable) was added as described in the WIndows install section
- Screenshot on German system "Systemfehler" means "System Error". "nicht gefunden" = "not found"

**Comment by GyulyVGC** [comment]
Weird situation. Have you added the `Lib` or the `Lib\x64` folder to your `LIB` env variable?

**Comment by jwesemann** [comment]
Yes, as descibed in the instructions for Windows - even if I do not understand why "Packet.lib" and "wpcap.lib" should affect runtime? I assumed that these are link libraries for development only?
I tested both places "npcapsdk\Lib" and "npcapsdk\Lib\x64"

Ich checked for wpcap.dll and found it as expected @ c:\windows\System32\Npcap

As as I mentioned: Wireshark finds and uses npcap.

**Comment by GyulyVGC** [comment]
It's the first time it happens this problem with all the right dependencies installed.

What I can suggest is to re-install sniffnet again through the installer but I doubt it'll solve the issue.

If you have Rust installed you could try to download it with `cargo`, but even in that case I think the issue is not in the installer, since other people successfully downloaded it with the installer and I tested it on different machines and everything was fine.

**Comment by GyulyVGC** [comment]
You mentioned you already had Npcap installed, I think the issue could be the compatibility between your different installation.

The default download options may not install Npcap in compatibility mode (have you selected "WinPcap API-compatible mode" during Npcap installation?)

But still you said Wireshark is working properly, so I don't what to suggest you

**Comment by jwesemann** [comment]
Solved: Reinstalling Npcap and selecting `WinPcap API-compatible mode` solved the issue. I was not aware that this setting had to be used. 

Thanks for you work and quick support. Have a nice weekend and Christmas time :-)
