### ISSUE TITLE
Build failure for ppc64

### ISSUE THREAD

**Issue by dutyrok** [GyulyVGC/sniffnet#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Hello. I get an error while has tried to build sniffnet 1.2.2 for ppc64 using ALT Linux Sisyphus. See [logs](https://git.altlinux.org/tasks/327845/build/100/ppc64le/log).  It occurs due to ring which 0.16.2 version [doesn't support](https://github.com/briansmith/ring/issues/1567) this arch. 

### How did you install the app?

built locally by cloning the repository

### Operating System

Linux

### Additional context

Version 1.1.3 has been built for ppc64 successfully. [Logs](https://git.altlinux.org/tasks/archive/done/_317/325478/build/1100/ppc64le/log).

**Comment by GyulyVGC** [comment]
So, if I understood correctly it's an upstream problem related to ring, right?

In this case, how could I help you? 
The only solution would be to manually downgrade ring in the lock file... did you try it?

**Comment by GyulyVGC** [comment]
I've run a cargo update this morning, I'll check better later if a newer version came out

**Comment by GyulyVGC** [comment]
Actually nope.
Yesterday a new version of `reqwest`, the crate using `rustls`, was released and Sniffnet is already up to date.
I think we have to wait until they release a new version with `ring` updated.

**Comment by GyulyVGC** [comment]
By the way, ring 0.16.20 is the latest version https://crates.io/crates/ring/versions

So we are already up to date

**Comment by GyulyVGC** [comment]
One more note: version 1.1.3 compiled successfully because it used `reqwest` without the `rustls-tls` feature.

If you place this line

`reqwest = { version = "0.11.16", features = ["json", "blocking"] }`

in place of the current `reqwest` import, you should be able to compile without problems.

The rustls-tls feature was needed because of other issues with some Debian distros.

**Comment by dutyrok** [comment]
Yes, it solves the problem ([log](https://git.altlinux.org/tasks/327845/build/200/ppc64le/log)). But I also want to check if it works using qemu ppc64 virt system.
I modify Cargo.toml the next way (also do `cargo update` to refresh Cargo.lock):
```diff
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -44,9 +44,14 @@ maxminddb = "0.23.0"
 confy = "0.5.1"
 serde = { version = "1.0.183", default_features = false, features = ["derive"] }
 rodio = { version = "0.17.1", default_features = false, features = ["mp3"] }
-reqwest = { version = "0.11.18", default-features = false, features = ["json", "blocking", "rustls-tls"] }
 dns-lookup = "2.0.2"
 
+[target.'cfg(target_arch = "powerpc64")'.dependencies]
+reqwest = { version = "0.11.20", features = ["json", "blocking"] }
+
+[target.'cfg(not(target_arch = "powerpc64"))'.dependencies]
+reqwest = { version = "0.11.20", default-features = false, features = ["json", "blocking", "rustls-tls"] }
+
```
Will these changes accept by you, if I create a pull request?

**Comment by GyulyVGC** [comment]
Yeah, looks good to me 👍

**Comment by dutyrok** [comment]
Ok, I will do a pull request as soon as check it on virt system.
