### ISSUE TITLE
can not detect the network adapter

### ISSUE THREAD

**Issue by freedom6927** [GyulyVGC/sniffnet#361]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

my installed version is windows. i have installed npcap. but when i open the app. the app cannot detect the network adapter. the only released selection is a address 127.0.0.1

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment]
Hi,
Does this mean that the initial page on the left only shows a single option?
Could you kindly provide a screenshot?

**Comment by freedom6927** [comment]
hi, this is the  screenshot

Giuliano Bellini ***@***.***> 于2023年8月30日周三 16:52写道：

**Comment by GyulyVGC** [comment]
I don't see your screenshot.
Anyway, are you sure you installed the latest version of npcap? (1.76)

**Comment by GyulyVGC** [comment]
Different sources online suggest to reinstall npcap in cases like this one. (example: https://ask.wireshark.org/question/14276/with-wireshark-32-on-windows-with-npcap-the-only-interface-is-the-loopback-interface/)

**Comment by l-33ter** [comment]
Had the same problem, every time I restart my computer the npcap(1.76) is installed... but is not recognized by Sniffnet - a simple reinstall, the npcap, and it works.

**Comment by GyulyVGC** [comment]
Amazing.

Thanks @l-33ter for the report!

**Comment by GyulyVGC** [comment]
Closing the issue.
@freedom6927 feel free to reopen if you don’t solve by reinstalling npcap.
