### ISSUE TITLE
Opens on a white screen

### ISSUE THREAD

**Issue by Headedbranch225** [GyulyVGC/sniffnet#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

When I open the app it shows a white screen with a black border then closes, shown here I have installed npcap 1.76 and I think the environment variable is correct.

https://github.com/GyulyVGC/sniffnet/assets/95239405/82fd33d1-3742-48e3-9fe9-83fc2351be05

![image](https://github.com/GyulyVGC/sniffnet/assets/95239405/d806a3cf-f404-42d2-ab66-4ba2c933cb06)

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment]
Hi @Headedbranch225 

Could you please open a terminal and launch Sniffnet from there?
I'd be helpful to obtain a textual output of the error.

**Comment by Headedbranch225** [comment]
I will when i get home from my family meal

**Comment by GyulyVGC** [comment]
You open a prompt and just paste there the executable path, then you press return

**Comment by Headedbranch225** [comment]
It just tries to open then closes as usual

**Comment by GyulyVGC** [comment]
No error message at all is printed in the terminal?

**Comment by Headedbranch225** [comment]
no message at all

**Comment by Headedbranch225** [comment]
could you use teamviewer to try and fix the problem?

**Comment by Headedbranch225** [comment]
![image](https://github.com/GyulyVGC/sniffnet/assets/95239405/8cc1936b-4dd3-4b56-bfe3-0ebfeec6668d)

**Comment by GyulyVGC** [comment]
Note that there is no need to click on sniffnet.exe, you can directly open the app clicking on the "Sniffnet" bundle.

Also, pay attention to your architecture and the version of Sniffnet you have installed (32-bit vs 64-bit).

Another workaround is the following.
This is a the same version of Sniffnet built using a different graphical renderer, since the default one (`wgpu`) may cause problems in some cases: 
https://github.com/GyulyVGC/sniffnet/suites/14909529200/artifacts/849640695

If you are still not able to solve the issue, I can try to help you tomorrow with Teamviewer.

**Comment by Headedbranch225** [comment]
what do you mean by the sniffnet bundle

**Comment by GyulyVGC** [comment]
It's the object containing sniffnet.exe and License.txt

**Comment by Headedbranch225** [comment]
I have the right architecture but I still don't understand what you mean by the object

**Comment by Headedbranch225** [comment]
Do I need to uninstall sniffnet before trying to install the other renderer one?

**Comment by GyulyVGC** [comment]
> I have the right architecture but I still don't understand what you mean by the object

The folder named "Sniffnet" in which the two files I mentioned are placed. 
Applications are usually opened by clicking on that object instead of directly clicking the .exe file, even if it should be the same thing.



> Do I need to uninstall sniffnet before trying to install the other renderer one?

Yeah

**Comment by Headedbranch225** [comment]
Thanks, It is working now

**Comment by GyulyVGC** [comment]
Perfect, I'm happy you can use Sniffnet.
What was the issue? The renderer or the click on sniffnet.exe?
Clicking on the .exe should work in theory but I'm asking for confirmation.
