### ISSUE TITLE
Display utilities that drive traffic

### ISSUE THREAD

**Issue by snooppr** [GyulyVGC/sniffnet#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

Do you know at least one GUI software on GNU/Linux that inspects traffic well? For example, it displays not only activity, but also the most common things: it displays which utility creates network activity? It seems there are none, unlike Windows OS (GUI utilities from Nirsoft).

To understand which utility is driving traffic, you have to run the cli with commands, for example, as in the screenshot (`lsof -i | grep part of the IP address`). How realistic is it to implement this in Sniffnet software?

![Без имени](https://github.com/GyulyVGC/sniffnet/assets/61022210/5bac73ec-2860-4942-aa3a-c0cffed8163e)
In this case, the network activity is created by the Signal software, but I learned about this from the CLI, not from Sniffnet

Rationale: All operating systems have GUI software that displays network activity and the application that creates it, with GNU/Linux problems.

Here is an example of a software utility from Nirsoft that contains less than 300Kb (It is clear and obvious what kind of software creates and drives traffic in Windows OS.).:
![111](https://github.com/GyulyVGC/sniffnet/assets/61022210/18a6144e-4a75-4dfa-9cdf-21686acb7e42)
tcplogview-x64

![2](https://github.com/GyulyVGC/sniffnet/assets/61022210/b2fe9e9d-3189-46bc-84a2-2531551015df)
networktrafficview-x64

**Comment by GyulyVGC** [comment]
Hi @snooppr and thanks very much for your interest in Sniffnet

We already have an issue open to track this feature request: #170 (to which I just added your considerations).
The feature is also tracked in the [project's roadmap](https://github.com/GyulyVGC/sniffnet/blob/main/ROADMAP.md), but is not planned for the short term.

The main concern behind this feature are that it's heavily platform-dependent and that often the available process names are not very meaningful (e.g., from what I see on macOS).

Closing as duplicate: please take #170 as reference.
