### ISSUE TITLE
[Request] More Port/Application Info

### ISSUE THREAD

**Issue by hbednar** [GyulyVGC/sniffnet#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

The below provide a lot of info on what application/protocol uses each port.
There is some overlap but, each provides some different info.

/etc/services
https://svn.nmap.org/nmap/nmap-services
https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml

### Is your feature request related to a problem?

At the moment there are a lot of ports that are not displaying any info against or appearing in the application panel.

![2023-9](https://github.com/GyulyVGC/sniffnet/assets/71215137/41d391da-e093-4acb-b1ba-28fdd899e629)

**Comment by hbednar** [comment]
> So, basically you want to be able to categorise what is currently labelled as "Other", right?

Yes to minimize other as much as possible and to move it into defined categories.

The three examples above are in very similar, if not the same format and could be periodically downloaded and saved in a text or other file.

The first example is already saved on the Linux os and could be filtered to find the right port. The other two could be added to it periodically to improve results

**Comment by GyulyVGC** [comment]
Following your suggestion, I decided to use Nmap services list to add traffic detection for more than 6000 services in #450

**Comment by Department-stack** [comment]
I would like the ability to give names to certain ports (preferably with range support ex: ports 60-68), so that certain services wont be under "other"
