### ISSUE TITLE
Is there a web version of sniffnet besides the client?

### ISSUE THREAD

**Issue by w2234f** [GyulyVGC/sniffnet#375]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Is there a web version of sniffnet besides the client?

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

**Comment by GyulyVGC** [comment]
Hi @w2234f 
Currently there is not a web version of Sniffnet.
Closing this issue as a duplicate of #57.
