### ISSUE TITLE
[Feature Suggestion] IPinfo's free IP database - IP to Country ASN

### ISSUE THREAD

**Issue by abdullahdevrel** [GyulyVGC/sniffnet#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

As Sniffnet uses country and ASN information of IP addresses, I think [IPinfo's free IP database](https://ipinfo.io/products/free-ip-database) would be able to provide tremendous value. 

The features of the [free IP to Country ASN database](https://ipinfo.io/developers/ip-to-country-asn-database):

- Provides full accuracy with daily updates and no IP range aggregation. The accuracy of IP data is provided on a granular level.
- Combines both country and ASN information in a single database.
- Comes in MMDB file format.
- The database structure is flat, tabular and consistent.
- Released under a commercially permissible CC-BY-SA 4.0 license.

Schema: https://ipinfo.io/developers/ip-to-country-asn-database

| FIELD NAME     | EXAMPLE                      | DATA TYPE | DESCRIPTION                                       |
|----------------|------------------------------|-----------|---------------------------------------------------|
| start_ip       | 1.0.16.0                     | TEXT      | Starting IP address of an IP address range        |
| end_ip         | 1.0.31.255                   | TEXT      | Ending IP address of an IP address range          |
| country        | JP                           | TEXT      | ISO 3166 country code of the location             |
| country_name   | Japan                        | TEXT      | Name of the country                               |
| continent      | AS                           | TEXT      | Continent code of the country                     |
| continent_name | Asia                         | TEXT      | Name of the continent                             |
| asn            | AS2519                       | TEXT      | Autonomous System Number                          |
| as_name        | ARTERIA Networks Corporation | TEXT      | Name of the AS (Autonomous System) organization   |
| as_domain      | arteria-net.com              | TEXT      | Official domain or website of the AS organization |

As the [IPinfo's IP to Country ASN database](https://ipinfo.io/developers/ip-to-country-asn-database) comes in `.mmdb` format, the rust MMDB reader library can still be used. The "free" in the *free* IP database is only related to the part that it is a reduced subset of the IP geolocation database and does not provide city-level data. There is no compromise with accuracy.

Please let me know what you think. If you need any assistance, I will be happy and glad to help.

Disclaimer: I am the DevRel of IPinfo. We also have a community dedicated to IP data usage in OSS projects.

### Is your feature request related to a problem?

The existing IP database does not provide daily updates, and I believe it does aggregate IP ranges. Due to the database's lack of full accuracy, there are possibilities of IP location discrepancies.

Example (As of writing this):

IP Address: 69.174.17.106 [(IPinfo.io/69.174.17.106)](https://ipinfo.io/69.174.17.106)

Current Provider's free service: Argentina

Current Provider's paid service: United States

**IPinfo's Free IP database**: Canada

Evidence: The lowest ping time from 600+ probe servers is in  Montréal, Quebec, CA.

Independent evidence from Ping.sx

![image](https://github.com/GyulyVGC/sniffnet/assets/111275753/39f6594b-6c26-4acd-8b93-a2c4bfce73b6)

**Comment by GyulyVGC** [comment]
Hi @abdullahdevrel first of all thanks very much for the very detailed and precise report, I really appreciate that.

Some concerns I'm noticing:
- the size of the DB is a bit high (if I'm not wrong it's around 47 MB) and this would negatively impact on the packed binary size. I know that probably the size overhead wrt the DB I'm currently using is due to the presence of more entries/major accuracy, but it still feels a bit too much.
- Even if the DB is updated daily, I'm currently distributing the MMDBs embedded into the binary, so given a version of Sniffnet the MMDB file wouldn't be updated anyway.

**Comment by abdullahdevrel** [comment]
I really appreciate you taking a look, @GyulyVGC 

Would it be possible for us to write a PR for the project that implements a database download mechanism during the installation process?

This will be a great feature because:

- It will enable you to ship smaller binaries without packaging a database in the project.
- Users will get full accuracy and updated data routinely if they update the IP database themselves.
- It will simplify code maintenance issues as the IP database will be downloaded from the client side and the update mechanism will be done by the user.

The plan I would suggest:

- During the installation, the database from IPinfo gets downloaded.
- During the installation process, we mention where the IP database is stored by mentioning the file path to the DB.
- The user is provided some level of documentation so they can update the database routinely. The file path to the IP database should be transparent and it is just a file they can overwrite to keep the IP data fresh.

Downloading the IP database is as simple as making a `curl`/`wget` call ([documentation](https://ipinfo.io/developers/database-filename-reference)):

```
curl -L https://ipinfo.io/data/free/country_asn.mmdb?token=<YOUR_TOKEN> -o country_asn.mmdb
```

**Addressing your concerns**

> wrt the DB I'm currently using is due to the presence of more entries/major accuracy, but it still feels a bit too much.

The cost of high accuracy is that we are including more granular information, and thus, the size of the binary is relatively large.  

The current two databases that you use account for a total of ~15 MB. While our database is significantly bigger. 

The size discrepancy is due to IP range aggregation. IP range aggregation works by clustering IP ranges ( for example, `/24`) into one geolocation. So, even if IP addresses of an IP address range fall into multiple countries, by doing IP address range clustering, providers simply pick the majority location of each IP address and assign it to the entire range. That is an accuracy compromise. This creates a new dimension of the problem, as range clustering does not account for IP corrections on an individual level.

We do not do range clustering; the database is fully accurate even though it is free. IP range granularity goes to even one IP address level (`/32` CIDR range).

Example:

```sql
SELECT *
FROM (
    SELECT *
    FROM ip_country_asn
    WHERE start_ip=end_ip
)
SAMPLE (5 ROWS)
```

| START_IP                    | END_IP                      | COUNTRY | COUNTRY_NAME   | CONTINENT | CONTINENT_NAME | ASN     | AS_NAME           | AS_DOMAIN      |
|-----------------------------|-----------------------------|---------|----------------|-----------|----------------|---------|-------------------|----------------|
| 2620:0:1cff:dead:beef::7ca0 | 2620:0:1cff:dead:beef::7ca0 | DE      | Germany        | EU        | Europe         | AS32934 | Facebook, Inc.    | facebook.com   |
| 2606:4700::6811:ffbf        | 2606:4700::6811:ffbf        | US      | United States  | NA        | North America  | AS13335 | Cloudflare, Inc.  | cloudflare.com |
| 2001:728:0:2000::8a         | 2001:728:0:2000::8a         | GB      | United Kingdom | EU        | Europe         | AS2914  | NTT America, Inc. | ntt.com        |
| 192.229.237.144             | 192.229.237.144             | US      | United States  | NA        | North America  | AS15133 | Edgecast Inc.     | edg.io         |
| 107.154.143.1               | 107.154.143.1               | BR      | Brazil         | SA        | South America  | AS19551 | Incapsula Inc     | incapsula.com  |

Now, if we implement an IP database download feature, you can remove the database packaged with the binary, which accounts for 15 MB.

Then, when the user installs the program, they can download the database directly from us after installation. Moreover, if we keep the downloaded database path transparent, users can regularly download our database using their own free token to keep the database updated. They can write a cronjob of sort that overwrites the IP database on a regular schedule.

> MMDBs embedded into the binary, so given a version of Sniffnet the MMDB file wouldn't be updated anyway.

I hope that you will consider implementing the download mechanism. The parent databases of the IP to Country ASN database are ASN database and IP to Geolocation database.

- The ASN database has changed by 0.116% since yesterday.
- The IP to Geolocation database changed by 0.004% since yesterday.

Considering the daily changes, these updates can add up. Sniffnet deals with sensitive information, so the project would greatly benefit from the increased accuracy provided by our database. 

---

Please let me know what you think.

**Comment by GyulyVGC** [comment]
While I got your point and actually the solution could be beneficial under certain point of views, I still prefer bundling the DBs to keep things easy for the average user.
I think the normal user is not interested in having such a fine grained granularity and I don't want to leave the burden to create a token and install in a pre-defined path.

A better solution is an hybrid one: in #365 I'm already implementing the possibility to choose a custom MMDB file for users who have a commercial database or want more precision, otherwise the embedded one will be used.
In this way, the average user can enjoy the app without having to worry about further installations/configurations, while more advanced users can download the MMDB file they prefer and later set the path to it via the new Advanced settings.

**Comment by GyulyVGC** [comment]
I thank you again very much for your proposal and assistance in providing such a detailed ticket.

However, as anticipated I think that #365 is the best tradeoff between complexity and completeness.

**Comment by abdullahdevrel** [comment]
@GyulyVGC Thank you very much again for considering us. I totally understand.

We will be cheering on from the sidelines :) Feel free to ping us anytime in the future, it will be an honor to help.

**Comment by GyulyVGC** [comment]
Hey @abdullahdevrel I was wondering if there could be a chance for a sort of collaboration between IPinfo and Sniffnet.

#365 was merged some days ago and I thought it can be nice to include in Sniffnet's settings a link  to the IPinfo website.

This would be beneficial for:
- my users to know where to get MMDB resources
- for IPinfo itself, since it'd be a sort of promoting chance to acquire new customers and to be highlighted as one of the leaders in this sector

Furthermore, if you are willing to start this collaboration, I'll be more than happy to highlight IPinfo as one of Sniffnet's sponsors in the README as well as the official website of the project.

I plan to release the next version of the app in a couple of months, so feel free to take your time to come to a decision 😃

**Comment by abdullahdevrel** [comment]
Hey @GyulyVGC,

Apologies for the late response. That is a fantastic proposal. I have emailed you (gyul****@gmail.com) to discuss the suggestion further.

Thanks!

**Comment by GyulyVGC** [comment]
Hey @abdullahdevrel I'm super happy you find the proposal interesting!

I just answered your email. 
I remain open for further discussion both here or via email.

**Comment by GyulyVGC** [comment]
@all-contributors please add @ipinfo for financial.
