### ISSUE TITLE
can't install on by windows 11 by cargo because of LINK : fatal error LNK1181

### ISSUE THREAD

**Issue by Schweik7** [GyulyVGC/sniffnet#39]
**Describe the bug**
can't install on by windows 11 by cargo because of LINK : fatal error LNK1181

**To Reproduce**

1. cargo install sniffnet 
2. LINK Error

**Screenshots**
<img width="876" alt="1669941919638" src="https://user-images.githubusercontent.com/25610011/205189238-5721d6f7-4ecb-4f87-b363-8cc534f0d9d3.png">

**Desktop (please complete the following information):**
 - OS: windows 11 22H2
 - rustc: 1.65.0

**Comment by GyulyVGC** [comment]
Have you installed the dependencies as described in the README?

**Comment by Schweik7** [comment]
I had tried install dependencies,but get some error.Then i got this:

**Comment by GyulyVGC** [comment]
Can you try installing Sniffnet through the installer? You can find it in the latest release.

**Comment by GyulyVGC** [comment]
Closing the issue for inactivity and since issues of this kind has already been solved a number of times.
To see other issue like this, filter by `windows` issue tag.
