### ISSUE TITLE
Lint your code with Clippy

### ISSUE THREAD

**Issue by auronandace** [GyulyVGC/sniffnet#4]
I've used clippy against your project and there are several lints that get triggered. These two can affect performance:

https://rust-lang.github.io/rust-clippy/master/index.html#single_char_pattern
https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone

Other lints also get triggered. Some of which will make your code more idiomatic and easier to read and reason about.

**Comment by GyulyVGC** [comment]
Done!
