### ISSUE TITLE
Feature Request: terminal mode

### ISSUE THREAD

**Issue by Brad7173** [GyulyVGC/sniffnet#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

I use webmin and have been looking for an app like this. Ettercap is the only other app I know of that can show network connections and display the country. This app will not work in webmin as it's more gui that command line. This would be 100% awesome!! to be able to use it in webmin terminal!!

### Is your feature request related to a problem?

Terminal or console mode!!

**Comment by GyulyVGC** [comment]
Hi @Brad7173, the latest command line version of Sniffnet is the 0.5.0... that version is still available on [crates.io](https://crates.io/crates/sniffnet) but has very limited functionalities with respect to the current version.

From issue #29:
> I am closing this issue as 'not planned'.
> After having taken into consideration different possibilities, I've come to the conclusion that it's better for me to focus exclusively on the GUI, as I feel like the vast majority of users is more interested on the graphical interface.
> Furthermore, I'm working to add new functionalities to the GUI which would require additional time to be re-implemented also for the TUI (and some of them wouldn't even be feasible).

Implementing all the functionalities both in GUI and in TUI would require me too much effort/time.
Thank you anyway for sharing your idea!
