### ISSUE TITLE
White Screen and Closing

### ISSUE THREAD

**Issue by boogeyoogeyman** [GyulyVGC/sniffnet#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Hello, I had issues with running the program (white screen and instant closing in particular), and after searching a couple of issues, I found out that the artifact link for skia renderer is expired. As I don't know how to build one myself, it would be nice if I could be provided with another link. Thanks.

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

### Additional context

Windows 11 - 23H2 Build 22631.2506

**Comment by GyulyVGC** [comment]
Hi @boogeyoogeyman 
Yes the problem probably is the graphical renderer as you already found out.
I had no idea those links had an expiration, thanks for made me notice it! 

I'm running a new action against the tiny-skin branch, I'll provide you with the download link as soon as it finishes.

**Comment by GyulyVGC** [comment]
Here you are @boogeyoogeyman — https://github.com/GyulyVGC/sniffnet/suites/18338999542/artifacts/1061225849

Let me know if this build of the app solves the issue.

**Comment by boogeyoogeyman** [comment]
Thanks for providing me with the link! They apparently expire after 3 months. It works fine now!
