### ISSUE TITLE
Perhaps make clear if it is an actual desktop requiring app, or runs through web-UI ?

### ISSUE THREAD

**Issue by jult** [GyulyVGC/sniffnet#434]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

For me this is totally unclear from looking at the site and pages here. Does it require a linux desktop environment, or can I have it run visually behind an nginx proxy for example?

### Is your feature request related to a problem?

Lacking instructions.

**Comment by GyulyVGC** [comment]
Hi @jult, thanks for your feedback.

Sniffnet is currently Desktop-only (see https://github.com/GyulyVGC/sniffnet/issues/57), and it's compatible with all the major operating systems.

I thought this was clear enough given that the [website Download page](https://sniffnet.net/download/) explicitly states that the app must be installed (listing the compatible systems) and that [this](https://github.com/GyulyVGC/sniffnet#required-dependencies) README section lists all the needed dependencies based on the target OS.

However, I'm agree with you that I could maybe write somewhere that it's Desktop-only for the moment (?).

**Comment by GyulyVGC** [comment]
Answers to this and other questions are now available in the [FAQ page](https://github.com/GyulyVGC/sniffnet/wiki/FAQ) of Sniffnet Wiki.
