### ISSUE TITLE
Issue: wpcap.dll was not found. (Windows 11)

### ISSUE THREAD

**Issue by FrikkyWasTaken** [GyulyVGC/sniffnet#502]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

![image](https://github.com/GyulyVGC/sniffnet/assets/72280325/28e6f148-f478-40c4-b7af-7b7d6668acbe)

I'm getting this error on windows 11. When downloading from both the website and the github.

I've reinstalled and the exact same thing happened.

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by FrikkyWasTaken** [comment]
Note: This happens after install completes on launch of the app

**Comment by GyulyVGC** [comment]
Hi @FrikkyWasTaken 

You have to install Npcap on Windows.

This is specified in the [required dependency](https://github.com/GyulyVGC/sniffnet/wiki/Required-dependencies) page of the user manual, as well as in the [install instructions for Windows](https://github.com/GyulyVGC/sniffnet/wiki/Install-on-Windows).
