### ISSUE TITLE
Sniffnet cannot open the file dialog 

### ISSUE THREAD

**Issue by Digitalone1** [GyulyVGC/sniffnet#503]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Sniffnet is not able to open a file dialog to select a destination for the capture file, or the ASN/County database. 

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

### Additional context

Installed from Arch upstream: https://archlinux.org/packages/extra/x86_64/sniffnet/

**Comment by GyulyVGC** [comment]
Not a good news.

This has almost for sure to do with [rfd](https://docs.rs/rfd/latest/rfd/).

I tested it on Windows, macOS, and DEB/GNOME and it works smoothly.

Could you verify from their docs that your backend is supported? They recommend to install `gtk3` on Arch, but it should only be required for the build and not for normal usage.

**Comment by GyulyVGC** [comment]
Note that _I think_ their docs isn't updated, since [they _should_ use XDG by default since 0.14](https://github.com/PolyMeilex/rfd/releases/tag/0.14.0).

So please refer to the doc section talking about the XDG backend.

**Comment by Digitalone1** [comment]
> DEB/GNOME and it works smoothly.

Where did it work smoothly? Did you test it in a Wayland environment?

**Comment by GyulyVGC** [comment]
X11 actually.

IIRC you are on Wayland, but in theory it should work even there.

**Comment by Digitalone1** [comment]
I have those installed:

```
$ pacman -Qs portal
local/libportal 0.7.1-2
    GIO-style async APIs for most Flatpak portals
local/libportal-gtk3 0.7.1-2
    GIO-style async APIs for most Flatpak portals - GTK 3 backend
local/libportal-gtk4 0.7.1-2
    GIO-style async APIs for most Flatpak portals - GTK 4 backend
local/xdg-desktop-portal 1.18.3-1
    Desktop integration portals for sandboxed apps
local/xdg-desktop-portal-gnome 46.0-1 (gnome)
    A backend implementation for xdg-desktop-portal for the GNOME desktop environment
local/xdg-desktop-portal-gtk 1.15.1-1
    A backend implementation for xdg-desktop-portal using GTK
```

**Comment by GyulyVGC** [comment]
Can you open Sniffnet from a terminal and see if there's any output when you try to open the file dialog?

**Comment by Digitalone1** [comment]
> Can you open Sniffnet from a terminal and see if there's any output when you try to open the file dialog?

No, there's no output.

I added the custom databases in the text config. Are the followings compatible?
- https://archlinux.org/packages/extra/any/geoip-database/
- https://archlinux.org/packages/extra/any/geoip-database-extra/

They're shown in red color. Maybe not supported?

![image](https://github.com/GyulyVGC/sniffnet/assets/25790525/74aec322-c199-4714-b993-c16d4a1b10f0)

**Comment by GyulyVGC** [comment]
GeoLite databases are supported, but you have to select the MMDB file format (which is also the only one that the file dialog will allow to select for those two fields).

**Comment by Digitalone1** [comment]
Never mind, I don't have those formats. 

Is there maybe any particular thing to do for dialogs to work? I mean, maybe specifying where portal files are located... 

[Here](https://archlinux.org/packages/extra/x86_64/sniffnet/) I don't see any portal package as dependency. 

As reported [here](https://gitlab.archlinux.org/archlinux/packaging/packages/sniffnet/-/blob/main/PKGBUILD?ref_type=heads), the app is built with:

```bash
cargo fetch --locked --target "$(rustc -vV | sed -n 's/host: //p')"
cargo build --frozen --release
cargo test --frozen
```

**Comment by GyulyVGC** [comment]
Honestly I don't know.
Maybe it's better to ask @PolyMeilex or open an issue in the [rfd repo](https://github.com/PolyMeilex/rfd).

**Comment by PolyMeilex** [comment]
Perhaps try to install `zenity` it is used in case portal backend fails.

**Comment by Digitalone1** [comment]
> Perhaps try to install `zenity` it is used in case portal backend fails.

Yes, it's working. Thanks.

But I suppose the issue still exists since the portal fails...

**Comment by GyulyVGC** [comment]
I'm happy you found a workaround.
Thanks @PolyMeilex for the help.

Closing the issue here since it's been partially solved and it's not directly related with Sniffnet.

**Comment by Digitalone1** [comment]
@orhun I suggest to add `xdg-desktop-portal` and `zenity` as sniffnet package dependency.

**Comment by orhun** [comment]
Done o7 thanks for the ping! 🐻
