### ISSUE TITLE
[BUG] can't open sniffnet on Arch Linux

### ISSUE THREAD

**Issue by xiaomx32** [GyulyVGC/sniffnet#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the bug
Opening sniffnet I get an error:

> `thread 'main' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-0.19.3/src/backend/wgpu_core.rs:724:18:
> Error in Surface::configure: Validation Error
> `
> Caused by: Parent device is lost
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### To Reproduce
Describe steps to reproduce the bug, e.g.:
1. Open terminal and type sniffnet

### Desktop
- Arch Linux x86_64
- DE: KDE Plasma 6.0.4
- WM: KWin (Wayland)
- NVIDIA GeForce GTX 1650

### Additional context
I installed with `pacman` and installed all dependencies

**Comment by GyulyVGC** [comment]
Hi, you can try fixing this problem by using an alternative graphical renderer.

To do so, set the environment variable `ICED_BACKEND=tiny-skia`.

**Comment by xiaomx32** [comment]
> Hi, you can try fixing this problem by using an alternative graphical renderer.
> 
> To do so, set the environment variable `ICED_BACKEND=tiny-skia` and let me know.

Sorry, I don't know what tiny skia is.
Where should I set this environment variable?

**Comment by xiaomx32** [comment]
> > Hi, you can try fixing this problem by using an alternative graphical renderer.
> > To do so, set the environment variable `ICED_BACKEND=tiny-skia` and let me know.
> 
> Sorry, I don't know what tiny skia is. Where should I set this environment variable?

I set this environment variable in the terminal and the app is run successfully!
Can you tell me what caused this？

**Comment by GyulyVGC** [comment]
`tiny-skia` is another graphical renderer supported by the GUI library used by Sniffnet.

Setting this environment variable is done just like any other environment variable.

If you don't know how to set them, check out https://wiki.archlinux.org/title/Environment_variables#Globally.
Note that you should set this variable in the configuration files, otherwise you'll have to reset it every time you want to run Sniffnet.

This problem was caused by your graphical drivers not properly supporting `wgpu`, which is the default renderer used by the application.

**Comment by xiaomx32** [comment]
You're right, just now I compiled the official example of wgpu and reported the same error.
Thank you for your answer.

**Comment by GyulyVGC** [comment]
No problem, I'm happy you solved the issue.

The `wgpu` renderer is slightly more efficient, so in case you are able to make it work, you can switch back setting the variable to
`ICED_BACKEND=wgpu`.

I suggest you to check out https://github.com/iced-rs/iced/issues/1618 for possible solutions.

If they don't work, just stick to `tiny-skia` 😁
