### ISSUE TITLE
`laggy interface after update`

### ISSUE THREAD

**Issue by overtube** [GyulyVGC/sniffnet#527]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

laggy interface on newer version that app, interface cannot lagg before update.
also.

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

### Additional context

app installed with latest version of``cargo`` also I try install with pacman, but lags won't gone, so also I try recompile, mdaybe I have some wrong cargo flags?

**Comment by GyulyVGC** [comment]
Hi @overtube on which version this problem occurs? Just on the last one (v1.3.0)?

And what do you exactly mean by lag?
Could you share a short video?

**Comment by overtube** [comment]
yes, ofc, version 1.3.0. low responsiveness of the interface with a slight delay in animations, when make some interaction.
[2024-05-06_04-33-04.mp4.zip](https://github.com/GyulyVGC/sniffnet/files/15215256/2024-05-06_04-33-04.mp4.zip)

**Comment by GyulyVGC** [comment]
Mm it seems really annoying... you can try setting an environment variable `ICED_BACKEND=tiny-skia` and see if it's better.
This environment variable is telling the GUI library to use an alternative graphical renderer.
But this is weird since the default renderer `wgpu` is usually more performant.

**Comment by overtube** [comment]
after add that variable app work normally again, as before update, how I can pass compile flag for recompile app with enabling that by default?

**Comment by GyulyVGC** [comment]
You don't need to recompile the app.
The renderer is chosen at run-time so it's enough to set the environment variable in a permanent way in your system, and that's it.
Remember that if for any reason you want to go back to the default renderer you can set the same variable to `wgpu`.
