### ISSUE TITLE
Can't run the program on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by ABADY1000** [GyulyVGC/sniffnet#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

I can't run sniffnet on my machine, it complains of GLIBC version!

I installed it by downloading Debian package `amd64` and install it using `dpkg`
```bash
sudo dpkg -i ./Sniffnet_linuxDEB_amd64.deb
```
When it didn't run I tried to install the dependecies mentioned in here 
![image](https://github.com/GyulyVGC/sniffnet/assets/31375142/7844381e-f4d9-40c4-be50-fc8b8f0019e1)
```bash
$ sudo apt-get install libpcap-dev libasound2-dev libfontconfig1-dev libgtk-3-dev
```
and it was installed successfully

When ever I try to run it this is what happen
```bash
 $ sudo sniffnet 
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by sniffnet)
```

My system details:
```bash
 $ uname -a
Linux ambat-PC 5.11.5 #1 SMP Sun Apr 4 12:39:37 +03 2021 x86_64 x86_64 x86_64 GNU/Linux
 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.7 LTS
Release:	16.04
Codename:	xenial
```

And I don't know exactly how to check GLIBC version, but here is something I tried:
```bash
 $ ls -al /lib/x86_64-linux-gnu/libc* | awk '{print $9}' 
/lib/x86_64-linux-gnu/libc-2.23.so
/lib/x86_64-linux-gnu/libcap.so.2
/lib/x86_64-linux-gnu/libcap.so.2.24
/lib/x86_64-linux-gnu/libcgmanager.so.0
/lib/x86_64-linux-gnu/libcgmanager.so.0.0.0
/lib/x86_64-linux-gnu/libcidn-2.23.so
/lib/x86_64-linux-gnu/libcidn.so.1
/lib/x86_64-linux-gnu/libcom_err.so.2
/lib/x86_64-linux-gnu/libcom_err.so.2.1
/lib/x86_64-linux-gnu/libcrypt-2.23.so
/lib/x86_64-linux-gnu/libcrypto.so.1.0.0
/lib/x86_64-linux-gnu/libcryptsetup.so.4
/lib/x86_64-linux-gnu/libcryptsetup.so.4.6.0
/lib/x86_64-linux-gnu/libcrypt.so.1
/lib/x86_64-linux-gnu/libc.so.6
```

Sounds my GLIBC version is old, how could I upgrade it safely? or is the problem somewhere else?

### How did you install the app?

downloaded one of the provided packages

### Operating System

Linux

**Comment by GyulyVGC** [comment]
Hi @ABADY1000 
>  $ sudo sniffnet 
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by sniffnet)

Is the output the same if you run without `sudo`?
Could you please also try `sudo -E sniffnet`?

**Comment by GyulyVGC** [comment]
If the error persists try updating the package with:

```
sudo apt-get update
sudo apt-get install libc6
```

**Comment by ABADY1000** [comment]
> Hi @ABADY1000
> 
> > $ sudo sniffnet
> > sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by sniffnet) sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by sniffnet)
> > sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by sniffnet) sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by sniffnet)
> > sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by sniffnet)
> 
> Is the output the same if you run without `sudo`? Could you please also try `sudo -E sniffnet`?

Hello @GyulyVGC , thank you for your reply

Yes it is the same output:
```bash
$ sniffnet
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by sniffnet)
```
And the other command also generated the same error
```bash
$ sudo -E sniffnet
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by sniffnet)
sniffnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by sniffnet)
```

**Comment by ABADY1000** [comment]
> If the error persists try updating the package with:
> 
> ```
> sudo apt-get update
> sudo apt-get install libc6
> ```

Here is the output from the second command after  updating the packages
```bash
$ sudo apt-get install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.23-0ubuntu11.3).
The following packages were automatically installed and are no longer required:
  gcc-5-base:i386 pandoc-data
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.
```

**Comment by ABADY1000** [comment]
It sounds like Ubuntu 16.04 is not supported, I run it on my another machine with Ubuntu 20.04 and it work directly

**Comment by GyulyVGC** [comment]
I'm happy you solved it somehow, even if the problem is still there... I imagine it's some dependency that's outdated and cannot be updated on older Ubuntu versions
