### ISSUE TITLE
Unable to start sniffnet

### ISSUE THREAD

**Issue by lightbearer1** [GyulyVGC/sniffnet#535]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

When I tried to start the program, there was no response, no error, and no pop-up window, as if I had never started it before. I am certain that I have correctly installed npcap and configured the npcap SDK environment according to readme's requirements, but it still cannot start. I think my problem may be similar to #364 , but the difference is that I don't even have a white screen appearing.
![image](https://github.com/GyulyVGC/sniffnet/assets/75633127/7fa4cb65-3fd0-4b62-9156-9eb7d933fdf4)
![image](https://github.com/GyulyVGC/sniffnet/assets/75633127/dc048a43-f30c-4675-8438-44832b31bfc4)
![image](https://github.com/GyulyVGC/sniffnet/assets/75633127/785c898b-7a0a-4c3a-b6b0-37810037f413)
https://github.com/GyulyVGC/sniffnet/assets/75633127/45ed0947-072a-4818-bef3-36aa9c78ddd3

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by lightbearer1** [comment]
> Hi @lightbearer1
> 
> If your problem is the same of the issue you mentioned, you'll be able to solve it by setting the environment variable `ICED_BACKEND=tiny-skia`. This will tell the application to use another graphical renderer instead of the default one that may be incompatible with your drivers.
> 
> Let me know.

YEEEES!!!It can work now,very thank you!

**Comment by GyulyVGC** [comment]
Awesome!
