### ISSUE TITLE
Make it possible to Increase zoom above 1.50

### ISSUE THREAD

**Issue by sang-shelton** [GyulyVGC/sniffnet#542]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

The appearance of the application is still small even after increasing the zoom to 1.50 from the settings. Similar issue [here](https://github.com/simplex-chat/simplex-chat/issues/3986)

Here is how the app looks like in 1.0 zoom

![Screenshot_2024-05-29_17-42-05](https://github.com/GyulyVGC/sniffnet/assets/154356073/f8adab7a-add5-494e-9cd0-74535e8e1ce2)

And here is 1.5

![Screenshot_2024-05-29_17-42-22](https://github.com/GyulyVGC/sniffnet/assets/154356073/27b5bdb8-2ccc-4381-87b7-c5db64c8b660)

 it would be nice if its 2.0 zoom.

**Comment by GyulyVGC** [comment]
Thanks for the suggestion, I'll keep this into account for the next release of the app.
