### ISSUE TITLE
Add shortcuts to allow zooming in/out (increasing font size etc)

### ISSUE THREAD

**Issue by corneliusroemer** [GyulyVGC/sniffnet#554]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

Bind the `ctrl` + `-` and `ctrl` + `+` shorcuts to increase decrease the zoom levels

<img width="268" alt="image" src="https://github.com/GyulyVGC/sniffnet/assets/25161793/55712fd8-82fd-45f7-8be1-44678dc63f6e">

### Is your feature request related to a problem?

I'm always frustrated when I can't quickly resize the font size of an application using the `ctrl` + `-` and `ctrl` + `+` shortcuts.

This is very important for visual accessibility. It's great that resizing is possible, it's just hard to discover and cumbersome to use (need to click on settings etc.)

**Comment by GyulyVGC** [comment]
Thanks for the suggestion, I'll gladly introduce this shortcut!
