### ISSUE TITLE
Make it clearer that countries need to be entered as 2-letter ISO country code, not as string

### ISSUE THREAD

**Issue by corneliusroemer** [GyulyVGC/sniffnet#555]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

Relabel the filter "Country" as "Country code" rather than "Country", as just country doesn't make it clear that one needs to enter 2-letter ISO codes. I typed `China` but couldn't find anything. Only much later did I discover I needed to type `CN`.

<img width="1053" alt="image" src="https://github.com/GyulyVGC/sniffnet/assets/25161793/e60c4827-98b3-4e1c-8045-1fee4df38858">

Feature #552 could help with this to some extent by showing the type of strings that are to be used for currently present data.

**Comment by GyulyVGC** [comment]
This is a good suggestion: older versions of the app showed countries in the table but now this is not anymore so evident.

As you pointed out, this can be solved by #552 and #354, so I don't think there's the need to also change the filter label, as it'd add some unneeded complexity.
