### ISSUE TITLE
Errors occured when trying to run sniffnet: invalid UTF8 [SOLVED] and failed to set hardware filter in promiscuous mode

### ISSUE THREAD

**Issue by FloRyuK0** [GyulyVGC/sniffnet#56]
**Describe the bug**
When I run Sniffnet after installing the dependencies, i got a error about utf 8

`An error occured! 
libpcap returned invalid UTF-8 : invalid utf-8 sequence of 1 bytes from index 55`

**To Reproduce**
Describe steps to reproduce the bug, e.g.:
1. Launch Sniffnet
2. Select IPV4/IPV6 and udp/tcp
3. Click on RUN

**Screenshots**
![image](https://user-images.githubusercontent.com/114009421/217082752-8e1b7b52-10f9-4d0b-ad39-50b58cb59107.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11 ]
 - Version [22H2]

**Additional context**

I understand that this is not a bug from Sniffnet but from libpcap, maybe the wrong version or maybe I missed something.
Can you help me understand the problem so i can solve it ?

**Comment by FloRyuK0** [comment]
I selected ethernet adaptater I do not have wifi on my pc, yes i tried to select another one but it's the same

**Comment by GyulyVGC** [comment]
The ethernet adapter should work fine. The problem is coming from libpcap side.
If you installed npcap and the npcap SDK from the link I provided in the README, it's really weird.
I'll try to investigate.

**Comment by FloRyuK0** [comment]
I unzip the npcap sdk in a new folder on my desktop and then add an environnement variable of the lib/x64 as a system variable and then reboot my pc

**Comment by GyulyVGC** [comment]
When the problem is related to npcap, usually Sniffnet does not even start. 
So I think there must be another reason.

**Comment by FloRyuK0** [comment]
Okay thanks i'll try in the next days to uninstall everything and reinstall to understand

**Comment by GyulyVGC** [comment]
Well. Let me know if you discover something new.
Last question: did you already have another version of WinPcap installed previously?

**Comment by FloRyuK0** [comment]
I never installed winpcap on this machine i discovered it with your project

**Comment by GyulyVGC** [comment]
I'm glad you found a way to solve the UTF-8 error.
Now I can suggest you to perform this 3 steps:
- update sniffnet to the latest version with `cargo install sniffnet` (yesterday I published a release featuring [many changes](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.1.0); these changes also include the update of the library used to interface with libpcap)
- if the update still doesn't solve the problem, try running the application in admin mode with `sudo sniffnet`; from the error you sent it seems you don't have the permission to inspect an adapter in promiscuous mode
- verify again that the adapter you are trying to sniff has at least one active IPv4 address

Let me know!

**Comment by FloRyuK0** [comment]
![image](https://user-images.githubusercontent.com/114009421/217460156-82244401-5706-4b63-b3ba-39fab7ddfbf4.png)
![image](https://user-images.githubusercontent.com/114009421/217460231-6b527073-8df0-4f70-b940-2af1b8deef74.png)
![image](https://user-images.githubusercontent.com/114009421/217460432-192fffcf-0368-4610-b4ec-2a96d465985f.png)

I'm sorry to tell you that it does not change anything.. 
Sorry for the screenshots in french but you can see that my ethernet is well active and that i run it in administrator mode.
Maybe a W11 bug ? or a windows service or firewall issue or I don't know ^^

**Comment by GyulyVGC** [comment]
It should work well on Windows 11 too. And yes, you correctly executed it in admin mode.
I feel sorry but at the moment I don't have any other recommendation for you to follow.
I'll leave this issue open and let you know if I discover something new.

**Comment by FloRyuK0** [comment]
Thank you, from my side I'll try to test and debug this ans let you know if i discover something too

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by FloRyuK0** [comment]
![image](https://user-images.githubusercontent.com/114009421/217614956-ab3b4d92-e5d8-4768-9e87-8c1425dc9b83.png)
On a fresh W11 virtual machine i got another error.. i don't understand anything now ^^

**Comment by GyulyVGC** [comment]
This error most of the times is solved downloading [Visual C++ Redistributable for Visual Studio 2015](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by FloRyuK0** [comment]
![image](https://user-images.githubusercontent.com/114009421/217618260-bebf73a8-1ba8-4374-b19b-dd09829bf2b5.png)
thanks i forgot visual c++ what an idiot ! 
now it's ok on my fresh VM, so I'll try to uninstall everything and test again on my real pc

**Comment by GyulyVGC** [comment]
Wooooow! Finally!!
Let me know, and good luck 🤞

**Comment by FloRyuK0** [comment]
that's exactly the same thing.. you can solve the issue i think that i'm missing something because it's working well on a new virtual machine

**Comment by FloRyuK0** [comment]
![image](https://user-images.githubusercontent.com/114009421/217630148-b57cf322-1dc1-48f8-8259-8055683d968b.png)

Houra !! 
Solved by downgrading npcap to 1.60
thanks to https://github.com/nmap/npcap/issues/628

**Comment by GyulyVGC** [comment]
Thank you very much, this can be really helpful for other people.
I’m glad you can now finally use Sniffnet after the time you lost!

**Comment by GyulyVGC** [comment]
> Houra !! Solved by downgrading npcap to 1.60 thanks to [nmap/npcap#628](https://github.com/nmap/npcap/issues/628)

@FloRyuK0  this is to inform you that Npcap v1.74 solved this problem, so you can update Npcap it if you want.
