### ISSUE TITLE
sniff net build fails on Mac M1 Sonoma

### ISSUE THREAD

**Issue by p357k4** [GyulyVGC/sniffnet#561]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

sniff net build fails on Mac M1 Sonoma (clean install) with command:

CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true RUST_BACKTRACE=1 cargo install sniffnet

rust version:

stable-aarch64-apple-darwin unchanged - rustc 1.79.0 (129f3b996 2024-06-10)

tail of build log:

   Compiling confy v0.6.1
error: failed to run custom build command for `sniffnet v1.3.0`

Caused by:
  process didn't exit successfully: `/var/folders/jz/ww6c9m5s4zd_86p_5wfjtdbr0000gn/T/cargo-installDgX4sx/release/build/sniffnet-c69e920c0c508f94/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=./resources/packaging/windows/graphics/sniffnet.ico
  cargo:rerun-if-changed=./services.txt

  --- stderr
  thread 'main' panicked at /Users/daniel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sniffnet-1.3.0/build.rs:83:13:
  Inappropriate service name found: pmsm-webrctl
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
     1: core::panicking::panic_fmt
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
     2: build_script_build::get_valid_service_fmt_const
               at ./build.rs:83:13
     3: build_script_build::build_services_phf
               at ./build.rs:48:19
     4: build_script_build::main
               at ./build.rs:23:5
     5: core::ops::function::FnOnce::call_once
               at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sniffnet v1.3.0`, intermediate artifacts can be found at `/var/folders/jz/ww6c9m5s4zd_86p_5wfjtdbr0000gn/T/cargo-installDgX4sx`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

### How did you install the app?

installed from crates.io

### Operating System

macOS

**Comment by GyulyVGC** [comment]
Hey @p357k4 this is the same error I'm getting on PR #560 which anyway isn't merged yet, and is due to the update of the `rustrict` dependency.
Installing from crates.io should download the latest published version which is still using the older version of that dependency... weird.

**Comment by GyulyVGC** [comment]
You can try building the Sniffnet from the release 1.3.0 commit: https://github.com/GyulyVGC/sniffnet/commit/066c54ac3ac965277535cc9001a433c90b0c9b51

This should the same state of the version published on crates.io, but for some reason you're compiling it with the newest `rustrict` version which I still have to fix.

**Comment by GyulyVGC** [comment]
Ok, I've found out why.
Cargo as default uses [caret requirements](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements), and this means that new minor versions can be used in place of the specified ones.
However, despite the update featured in #560 being a minor update, it breaks some tests I wrote in the build script, making the compilation fail.

As a workaround, you can build Sniffnet from the commit I provided you, or alternatively you can download a bundle from sniffnet.net/download.

I'll publish a new Sniffnet version in a few days, and I'll make sure to use more strict version requirements this time.

**Comment by GyulyVGC** [comment]
@p357k4

An even better solution: using the [--locked flag](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile).

I was able to verify that running 

```sh
cargo install sniffnet --locked
```

fixes the issue.

I'll update the install instructions on the README including this trick.

**Comment by p357k4** [comment]
@GyulyVGC, thank you.

I confirmed that both solutions work for me. :)
