### ISSUE TITLE
Problem with Arch Garuda Linux 

### ISSUE THREAD

**Issue by HerbJul** [GyulyVGC/sniffnet#563]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

/home/main-builder/pkgwork/src/SwiftShader/src/Vulkan/libVulkan.cpp:3910 WARNING: UNSUPPORTED: pProperties->pNext sType = 1000212000
/home/main-builder/pkgwork/src/SwiftShader/src/Vulkan/libVulkan.cpp:3910 WARNING: UNSUPPORTED: pProperties->pNext sType = 1000212000
fish: Job 1, 'sniffnet' terminated by signal SIGSEGV (Adressbereichsfehler)

### How did you install the app?

built locally by cloning the repository

### Operating System

Linux

### Additional context

Installation with Octopi or Cargo went wrong. I can't start the app and no error message appears 

sniffnet[155598]: segfault at 1c ip 000077a1d0dd11b6 sp 00007ffd0fa8f660 error 4 in libvk_swiftshader.so[77a1d0d7b000+bca000] likely on CPU 2 (core 0, socket 0)

**Comment by GyulyVGC** [comment]
Hey @HerbJul, the Vulkan warnings are suggesting that there are some incompatibilities between the GUI library and your graphical renderer.
Such issues are usually solved by setting the environment variable `ICED_BACKEND=tiny-skia`.
Let me know.

**Comment by HerbJul** [comment]
Microsoft Copilot helped me 

Terminal: $export ICED_BACKEND=tiny-skia cargo run

Now it works great 😎

**Comment by GyulyVGC** [comment]
Yeah, you should also be able to set that environment variable permanently by modifying you OS configuration files.
Anyway, I'm glad we solved the issue 🎉
