### ISSUE TITLE
Confirm stopping capture when window is closed

### ISSUE THREAD

**Issue by simmonsm** [GyulyVGC/sniffnet#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

if you accidentally click the window close X when doing a network capture it doesn't ask for confirmation and just exits the application unlike when you use the left arrow icon and it asks whether you wish to quit the capture.

**Comment by GyulyVGC** [comment]
Hi @simmonsm, this is actually a really nice idea.
I think I will implement it for the next release of the app.
