### ISSUE TITLE
The program shows a white screen and crashes upon opening

### ISSUE THREAD

**Issue by swola** [GyulyVGC/sniffnet#583]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

The program shows a white screen and crashes upon opening
I have installed npcap and configured the npcap SDK environment
I try to set the environment variable ICED_BACKEND=tiny-skia but it still crashes.
use the sniffnet Windows_64-bit.msi v1.3.1

![93cfdfd3b77dd52911a93778957f571](https://github.com/user-attachments/assets/4a9b4374-2d1c-4ecc-8e36-b003b43ee270)

no log output
![b265a2456cea9f196a1f6969ecb0504](https://github.com/user-attachments/assets/f8a5ac75-31a2-45ff-8987-7627f77116e2)

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

### Additional context

Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz
Windows 10  21H2 19044.1826

**Comment by GyulyVGC** [comment]
I'm sorry to see that also setting the ICED_BACKEND isn't helping 😞 
You don't see any output because of #578, but actually it'd be interesting to see some error trace in this case...

**Comment by GyulyVGC** [comment]
Hey @swola I just built a new version of the app for you.

Here you are: [Sniffnet_Windows_64-bit.msi.zip](https://github.com/user-attachments/files/16600473/Sniffnet_Windows_64-bit.msi.zip)


It is built against commit https://github.com/GyulyVGC/sniffnet/commit/0c67e7e6366eb63ef58cc6621845ec7e3cfbad4c on the [`windows-debug`](https://github.com/GyulyVGC/sniffnet/tree/windows-debug) branch, and using this one you should be able to see some logs in your terminal so that hopefully we can understand and fix the issue.

**Comment by swola** [comment]
Thank you
![10aa88b6b4a20fc35953a78680ba093](https://github.com/user-attachments/assets/50435564-dc9c-4730-91bf-93f42c96df19)

It looks like libpcap returned invalid UTF-8 when list device or something wrong in CStr::from_ptr
![image](https://github.com/user-attachments/assets/5c594819-a9ea-44a1-8a9f-aff7906b0254)

I try to use pcap:Device in rust but failed,maybe it neet to install visual studio (I don't know how to use Rust)
![4255779c50e9347b33397d93d7f7c67](https://github.com/user-attachments/assets/f23d04b8-fda6-403a-b36d-f7865e7f74a7)

**Comment by GyulyVGC** [comment]
Mm, it seems that your Npcap installation still have some problems.

Are you sure you installed Npcap in WinPcap compatible mode as described in the [guide](https://github.com/GyulyVGC/sniffnet/wiki/Install-on-Windows)?
However, the Npcap SDK and visual studio are only required for the build, but you don't need them to run the .exe app.
Only Npcap is required.

Another thing you can do to solve the UTF-8 error is to check the box "Beta : use unicode utf8 format" in windows regional options, as described in #120.

**Comment by swola** [comment]
Thank for you help it works by checking the box "Beta : use unicode utf8 format" in windows regional options
![31ef39df354c63491b783bc8e023f30](https://github.com/user-attachments/assets/f97ab8b8-2dc8-4443-9877-f88c31594d1d)
