### ISSUE TITLE
Question: How do I know which application is making the network call

### ISSUE THREAD

**Issue by dev-artisan** [GyulyVGC/sniffnet#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

Hi I've just started using the window version.
Great work.
I just wanted to know if there was a way to know which executable is making the network call, and if there isn't a way to tell from the app now, can this be a feature?

Thanks

**Comment by GyulyVGC** [comment]
Hey @dev-artisan at the moment there isn't a way to see which process is using network connections.
Of course this can be considered a feature to implement, and in fact it's in the project's roadmap and has also been reported in other issues.
Please refer to #170 for more info and updates about this.

**Comment by dev-artisan** [comment]
> Hey @dev-artisan at the moment there isn't a way to see which process is using network connections. Of course this can be considered a feature to implement, and in fact it's in the project's roadmap and has also been reported in other issues. Please refer to #170 for more info and updates about this.

Awesome thanks for that
