### ISSUE TITLE
After Installation I got  this error: wpcap.dll was not found

### ISSUE THREAD

**Issue by condecito** [GyulyVGC/sniffnet#606]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

After install the sniffneton windows 11 x64 I try to open but i got this message error:   
![image](https://github.com/user-attachments/assets/ddc96de0-002e-4c22-a2ba-9b861a67d01f)

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment]
Which Windows version @laniakeadev
