### ISSUE TITLE
Add AS Name into Results

### ISSUE THREAD

**Issue by m-cameron** [GyulyVGC/sniffnet#62]
Please consider to append ASN information into the results.

You can get the free ASN database from https://lite.ip2location.com/database-asn?lang=en_US

**Comment by GyulyVGC** [comment]
This is actually one of the features I will implement in v1.2.0.
Other info that will be added are:
- MAC addresses
- rDNS lookups of the remote address

I think I will implement a more detailed page for each of the sniffed connections with these info and their ASN.
If you have other ideas, you can share them without any problem.

**Comment by acolombier** [comment]
I am very interested in the rDNS feature! Is it something you need help to develop? I'd be happy to give it a go

**Comment by GyulyVGC** [comment]
> I am very interested in the rDNS feature! Is it something you need help to develop? I'd be happy to give it a go

Thank you very much for your proposal, but I've already tried to implement this feature and it is pretty straightforward thanks to a crate that performs rDNS lookups.

For v1.2.0 I have in mind a larger set of features which will include a new page with a search bar to select a connection to inspect and it's something pretty big and I would like to start it myself.

I will tag you when I'll have something ready (probably in some weeks or a few months) and at that point it'd be amazing to collaborate.

In the meantime, if you really want to help, it'd be nice to write some unit tests for the app (see [here](https://github.com/GyulyVGC/sniffnet/blob/main/src/enums/app_protocol.rs#L160) for an example of unit tests by @colin99d, to be written at the end of the file with the functions interested by tests).

**Comment by acolombier** [comment]
That sounds good to me - I will submit some for the `enums` crate - can see few low hanging fruits in there!

**Comment by GyulyVGC** [comment]
> That sounds good to me - I will submit some for the `enums` crate - can see few low hanging fruits in there!

Yep, that should be an easy way to start, thanks very much!

**Comment by GyulyVGC** [comment]
[A new release](https://github.com/GyulyVGC/sniffnet/releases/tag/v1.2.0) including Autonomous Systems and rDNS lookups has just been published!
