### ISSUE TITLE
Issue with using the app

### ISSUE THREAD

**Issue by Ucanspam** [GyulyVGC/sniffnet#631]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

Hello, 
I've followed the install instructions given on [that page](https://github.com/GyulyVGC/sniffnet/wiki/Install-on-Windows), everything ran smoothly but when I tried to open the app, it just opens an empty Sniffnet window that closes just a few second after.
Then nothing more :(
Any clue what's going on?
Thanks for your help.

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment]
Hi @Ucanspam maybe it's a problem with your graphical card.

Try setting the `ICED_BACKEND=tiny-skia` environment variable and let me know if it fixes the problem.

**Comment by Ucanspam** [comment]
thanks for your quick reply Giuliano,
Hmm... how, where do I check that variable?

**Comment by GyulyVGC** [comment]
You can check this guide: https://www.howtogeek.com/787217/how-to-edit-environment-variables-on-windows-10-or-11/#how-to-edit-environment-variables

**Comment by Ucanspam** [comment]
it works, congrats!

What is that variable for?
Can I keep it, should I remove it some day ?

**Comment by GyulyVGC** [comment]
The variable just tells Sniffnet to use a different graphical renderer for the user interface (`tiny-skia` over `wgpu`).

This is because your graphical card is probably not up to date or simply it doesn't support `wgpu`.

You can keep that variable, it's not a problem and it doesn't have any other consequence on your PC.

**Comment by Ucanspam** [comment]
oh thx for the explanations.
My Asus laptop is 10 years old and it's true I can't update the nvidia driver anymore.
Thx for your support Giuliano.
Good evening ;)

**Comment by GyulyVGC** [comment]
I'm happy we made it work 🎉 

Have a good day!
