### ISSUE TITLE
System Error - .dll file missing

### ISSUE THREAD

**Issue by rav-i** [GyulyVGC/sniffnet#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### What's the problem?

![image_2024-10-19_133951985](https://github.com/user-attachments/assets/cd9b1f06-4229-4780-925d-1f92eb161c78)

### How did you install the app?

downloaded one of the provided packages

### Operating System

Windows

**Comment by GyulyVGC** [comment]
Hi @rav-i this is because you have to install Npcap, as described here: [Install on Windows](https://github.com/GyulyVGC/sniffnet/wiki/Install-on-Windows).

I'm closing this issue as duplicate, let me know if you encounter further problems.
