### ISSUE TITLE
Suggestion for Improving Post-Installation Instructions

### ISSUE THREAD

**Issue by kadowakiBNG** [GyulyVGC/sniffnet#655]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the solution you'd like

In the “Alternative Installation Methods” section of the README, it would be helpful to clarify that, after installing on macOS, users need to launch sniffnet from the command line. Since this installation method does not register the application in the Applications folder, users may find it a bit unclear how to start using the tool.

For example, I suggest updating the “Install on macOS” page in the Wiki to include the steps for launching the application after installing it via Homebrew.

**Comment by GyulyVGC** [comment]
Thanks for the suggestion.

Done 👍
