### ISSUE TITLE
dont compile on Ubuntu 2204 

### ISSUE THREAD

**Issue by dominix** [GyulyVGC/sniffnet#66]
**Describe the bug**

just typed "cargo install sniffnet"

**To Reproduce**
cargo install sniffnet

**Expected behavior**
compile sniffnet cleanly

**Screenshots**  
...
   Compiling iced_core v0.7.0
   Compiling wgpu-hal v0.14.1
   Compiling iced_futures v0.5.1
   Compiling iced_style v0.6.0
   Compiling iced_native v0.8.0
   Compiling image v0.24.5
   Compiling ipnetwork v0.18.0
   Compiling smithay-clipboard v0.6.6
   Compiling sctk-adwaita v0.4.3
   Compiling confy v0.5.1
   Compiling maxminddb v0.23.0
   Compiling iced_graphics v0.6.0
error[E0658]: generic associated types are unstable
  --> /home/koublaski/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_graphics-0.6.0/src/image/storage.rs:12:5
   |
12 |     type State<'a>;
   |     ^^^^^^^^^^^^^^^
   |
   = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `iced_graphics` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `sniffnet v1.1.0`, intermediate artifacts can be found at `/tmp/cargo-installT3ViYm`

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows] 
  linux Ubuntu 
  Distributor ID:	Ubuntu
  Description:	Ubuntu 22.04.1 LTS
  Release:	22.04 
  Codename:	jammy

 

**Additional context**

I have tried to  "rustup update" but it doesn't change nothing.

**Comment by GyulyVGC** [comment]
Generic associated types has actually been stabilised in the newest Rust versions.
Can I see the error _after_ you updated your version of Rust? If it's the same, try restarting your shell. I don't get how it could tell you that GAT are still unstable.

**Comment by GyulyVGC** [comment]
Check to have the latest version with 
```sh
rustc --version
```

**Comment by dominix** [comment]
rustc 1.63.0

**Comment by dominix** [comment]
rustup update
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: cleaning up downloads & tmp directories

but still 
#  rustc --version
rustc 1.63.0

**Comment by dominix** [comment]
rustup update stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2023-02-09, rust version 1.67.1 (d5a82bbd2 2023-02-07)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
 29.3 MiB /  29.3 MiB (100 %)  21.4 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 67.8 MiB /  67.8 MiB (100 %)  21.4 MiB/s in  3s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 19.3 MiB /  19.3 MiB (100 %)   3.5 MiB/s in  5s ETA:  0s
info: installing component 'rust-std'
 29.3 MiB /  29.3 MiB (100 %)   8.1 MiB/s in  3s ETA:  0s
info: installing component 'rustc'
 67.8 MiB /  67.8 MiB (100 %)   8.3 MiB/s in  8s ETA:  0s
info: installing component 'rustfmt'

  stable-x86_64-unknown-linux-gnu installed - rustc 1.67.1 (d5a82bbd2 2023-02-07)


$ rustc --version
rustc 1.63.0



I may have gotten something wrong, shouldn't I have a 1.67.1 rustc ?

**Comment by dominix** [comment]
ubuntu is a complete mess regarding rust package management. part of it are in deb, other are in snap and dont interpolate correctly. 

I just removed rustc cargo and rustup and installed all from https://sh.rustup.rs  and now it compile  cleanly. sorry for the noise.

**Comment by GyulyVGC** [comment]
> I just removed rustc cargo and rustup and installed all from https://sh.rustup.rs and now it compile cleanly. sorry for the noise.

Don't worry at all! I'm glad you solved it!
