### ISSUE TITLE
Add option to quit sniffnet using ctrl+q

### ISSUE THREAD

**Issue by roland-rollo** [GyulyVGC/sniffnet#68]
I would be very thankful if I could close `sniffnet` using keys combination: ctrl + q.

**Comment by GyulyVGC** [comment]
Is there a specific reason you should close it with shift+q instead of ctrl+q?
On which system are you running?

**Comment by roland-rollo** [comment]
Damn, my bad. Yeah I should sway ctrl+q, not shift. Corrected my mistake. Thanks.

**Comment by GyulyVGC** [comment]
No problem. If I recall correctly you already mentioned it in a past issue. So I assume you are still running on Linux.
I'll let you know you as soon as I have updates on this.

**Comment by roland-rollo** [comment]
Yes, I use Linux (Arch Linux) with Sway (tiling window manager, so only keys shortcuts to close window). Take as much time as you need, and thanks for remembering me. New version is dope.

**Comment by GyulyVGC** [comment]
Oh, now I got your pain. 
I will definitely try to do something for you.

**Comment by roland-rollo** [comment]
Yup, it's working. thanks!
