### ISSUE TITLE
Publish the project on DockerHub 

### ISSUE THREAD

**Issue by AmadeusGraves** [GyulyVGC/sniffnet#76]
**Describe the solution you'd like**
It would be nice if Sniffnet was published on DockerHub so that you can publish a docker container locally from the published image. 

**Additional context**
You can publish the image from GitHub: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

**Comment by GyulyVGC** [comment]
Duplicate of #69.
However I'll leave it open for possible further discussions!

**Comment by GyulyVGC** [comment]
Due to inactivity I'm closing the issue.
Keep #69 as a reference for this problem!
